### ISSUE TITLE
Neither Tel nor Email is accepted

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#1008]
See screenshots. I was on a call with this person and seen the input. First she entered a long email address then the error came up, Then we tried with tel number she entered a tel number like this  +12919739723729 which was very long. Both times the error comes up and it seems to not clear the entries. Even after a reinstall and trying to add a short email address it did not work. 
![WhatsApp Image 2022-08-17 at 10 21 37](https://user-images.githubusercontent.com/3283800/185061075-ddc84578-97b8-41a8-a4cd-9d046e0d40ed.jpeg)
![WhatsApp Image 2022-08-17 at 10 12 50](https://user-images.githubusercontent.com/3283800/185061090-83484743-dcc6-4fd4-9202-9ff444723c61.jpeg)

**Comment by Elforama** [comment]
The email issue has been fixed already.

I'm guessing the telephone is too long. We check for a specific format I think.

**Comment by EngrTaofeek** [comment]
> The email issue has been fixed already.
> 
> I'm guessing the telephone is too long. We check for a specific format I think.

It is the same issue but it has been fixed. For now the only way to sign up is from the keyboard with the Go button.

**Comment by sebastiangaertner** [comment]
We need to increase this number . Emails and tel number can be significantly longer.

**Comment by sebastiangaertner** [comment]
Can we deploy the fix?

**Comment by EngrTaofeek** [comment]
@sebastiangaertner there is no restriction on length of emails(Emails could be any length actually). Also see attached image for why phone number is between 7 and 15
<img width="1440" alt="Screenshot 2022-08-23 at 11 14 26" src="https://user-images.githubusercontent.com/38661872/186133412-e3423af6-213e-4a9c-860c-08ebec18cfd8.png">

**Comment by EngrTaofeek** [comment]
The main bug has been fixed. I would just round up some other minor updates and conclude with Jonathan so we should be able to make a release today.
