### ISSUE TITLE
Map Stutters After Sync Button Pressed

### ISSUE THREAD

**Issue by AndroidDev77** [Greenstand/treetracker-android#103]
Scrolling across the map is smooth until you attempt to sync after you press the sync button the map has a high latency and will sometimes crash out.

Replicate
1. Open App
2. Press Settings button
3. Press Sync Button
4. Press back button
5. Pan across map.

Version: Master Branch 06/15/18
OS: Android 8.0.0

**Comment by deepwinter** [comment]
I've confirmed the stutter.

In the current app sync does not continue in the background, since it's not in a service.  It's not clear why the map is slow after sync begins, could be a memory leak.

**Comment by deepwinter** [comment]
Recommend investigating a memory leak here.  This may be resolved simply by moving to kotlin coroutine

**Comment by Davidezrajay** [comment]
@AndroidDev77 can you see if this is still happening after we moved to Kotlin?

**Comment by AndroidDev77** [comment]
Alright I will
