### ISSUE TITLE
Show Planter_ID on user profile in app

### ISSUE THREAD

**Issue by JonTrimarco** [Greenstand/treetracker-android#1035]
This is coming from both Fairtree and Kijani Forestry. Our work would be a lot easier if we could have new planters send us the planter_id that is generated for their account to streamline and shore-up the onboarding process. This would also help us troubleshoot around double-accounts. 

Specific request: 
Display the unique planter_ID (and/or subsequent planter identifier) number next to (or under) the planters name on each account (on the user profile tiles) on the app for the planter themselves to see.

**Comment by Elforama** [comment]
We currently show this info on each profile tile. In the image below, the planter ID is "handle3@test"

![Screenshot_20221208_183243](https://user-images.githubusercontent.com/6439445/206588929-ccfd021d-f633-4203-b4a8-0b8bcc960f76.png)
