### ISSUE TITLE
Sign up Redesign

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#104]
We need to discuss...
We are having problems with people being able to sign in, these problems mostly do to the illiterate state of our users / and that they don't have emails etc.

Also, we aim to support users that use a village phone. Ideally, we have a photo of the planter and their phone number.

**Comment by ryan-beckett** [comment]
@Davidezrajay: Is having an email address that much to ask? Won't they need one for mobile payments in the future anyway?

We need to have a password confirmation field in the sign-up form.  It would also be convenient to have the password field to have show/hide functionality. You can assign me to this issue.

**Comment by Davidezrajay** [comment]
Our biggest challenge is that our target audience is indigenousness people who have had little to no contact with any technology, for them requiring an email is a lot to ask. For a village coordinator, email is ok.

Payments are currently being sent via phone number. Services like Mpesa require a name (spelled correctly) and a phone number. 

Ideally we would I have a way authenticate the device and then require a photo of the user with their name and number. Currently, the planters may be getting scammed by people who are technically savvy. Primary questions we are answering now: **who planted what where**

Needs some more thought

**Comment by Davidezrajay** [comment]
I think this will work
On Sign up Page change email requirement 

- [ ]  Require email or phone number
- [ ] Remove password need

**Comment by deepwinter** [comment]
I think it's going to be necessary to show who is signed in, we currently don't show that to the user or allow them to change it.

**Comment by Davidezrajay** [comment]
That is a problem... 
What about:
- Auto Sign Out - after hours inactive 

- Require sign-in based on Email or Phone number

Ideally, capture a selfie for the sign in - or is that going to be a too much work for now.

**Comment by deepwinter** [comment]
Do we want a selfie with each sign-in ?  We can do it pretty easily.

**Comment by deepwinter** [comment]
@sebastiangaertner the use case you are describing is what the solution above is created to address.

**Comment by sebastiangaertner** [comment]
Fantastic 
--
Sent from myMail for Android Tuesday, 11 September 2018, 08:27AM +03:00 from zaven  notifications@github.com :

**Comment by deepwinter** [comment]
Redesign has been implemented, there are likely other minor issues to be logged before it goes live.
