### ISSUE TITLE
App Slowing down

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#105]
Sam from Tanzania reports that app slows down once the user takes several images. If a user takes pictures of a few hundred trees the app becomes so slow that it is "very boring" and all most unusable. 

Closing the app and restarting it seems to help. 

Sam downloaded an app called Parallel Space and runs the Tree Tracker app inside of it. Using Parallel Space the Tree Tracker runs much faster but can't load the map.

**Comment by Davidezrajay** [comment]
Tree Tracker app running inside of the Parallel Space app seems to work much faster and load to the map just fine, however, the primary_location id and photo_Id are null. Lat/Long is also recorded to an extra eight decimal places.
 - **From our app:**
 POINT (37.573689 -3.642785)
 https://treetracker-dev.nyc3.digitaloceanspaces.com/5740.jpg

- **From our app in Parrell Space:**
POINT (37.04862335527859 -3.112267596280947)
https://treetracker-dev.nyc3.digitaloceanspaces.com/2018.06.27.15.11.44_daca7733-fbdf-4d1f-a05b-fde463d8dfdd_IMG_20180627_150319_1986178489.jpg

**Comment by dezidaisy** [comment]
Maybe we can use this link:
https://medium.freecodecamp.org/how-we-reduced-memory-footprint-by-50-in-our-android-app-49efa5c93ad8

**Comment by Davidezrajay** [comment]
Slowing after 200 trees... 300 trees are nearly impossible to track in a day due to app speed. 
Working in Parrell Space, Sam is able to 800 trees per day.

**Comment by deepwinter** [comment]
The problem is that the map is trying to show all the trees.  This isn't necessary, and instead should be using clustering to display the tree points until you zoom in past a certain level.

**Comment by deepwinter** [comment]
Analyze similar to what is proposed in #118

**Comment by Davidezrajay** [comment]
This is fixed
