### ISSUE TITLE
Feature to capture height not working properly.

### ISSUE THREAD

**Issue by nprude** [Greenstand/treetracker-android#1069]
**Describe the bug**
Feature to capture tree height not working.  After hitting the button on the upper right corner of capture page, the progress bar is displayed at 0%, but quickly vanishes without any progress.  I am guessing that this button is related to the following requirement:
[Capturing tree height when tracking tree growth](https://github.com/Greenstand/treetracker-android/wiki/Product-Documentation)
A optional feature of the app to track the height of the tree is presented if the feature is turned on. This feature takes the user to a screen after taking a picture of an individual tree being tracked that has a vertical bar containing 5 different colors sections. Tapping on these section sets a color coded height value of the tree being captured. The colors used are green, purple, yellow, blue and orange. Each section of the bar (different colors) each represent 50 cms (half meter) to capture the height metric of the tree.
**To Reproduce**
1. Launch the Tree Tracker on Android.
2. Create user.
3. On Capture page, take a picture and hit green approval button.
4. Hit the green button in the upper right corner of Capture screen.

**Expected behavior**
This feature takes the user to a screen after taking a picture of an individual tree being tracked that has a vertical bar containing 5 different colors sections. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. Techno F?-)] Motorola G Play 
 - OS: [e.g. Android Version: ]11
![Uploading Screenshot_20230124-170404.png…]()

**Additional context**

**Comment by EngrTaofeek** [comment]
Hi @nprude this feature was predominantly used in Kisiki Hai Treetracker. Not all organisations use this feature so we decided not to put it in the default capture flow. However the screen is present and would be available through our custom organisation when it is ready so any organisation that needs this would indicate and it would appear in their capture flow.
