### ISSUE TITLE
Storage Issues

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#108]
App saves data in phone storage when phone storage is full app stops.

Current Feild solution: upload data and delete the images.

Sam's phone has 800mb of storage and holds around 450 to 500 data points it freezes.

**Comment by Davidezrajay** [comment]
Possible option is to save via SD card

**Comment by deepwinter** [comment]
images should be deleted off the phone

**Comment by deepwinter** [comment]
regarding the SD card, there is no guarantee that a given phone will even have an SD card.

**Comment by Davidezrajay** [comment]
Issue: that they are exceeding storage before they are able to get to a network before they can upload...

No easy solution. This is an enhancement - certainly not a priority now...

**Comment by ryan-beckett** [comment]
I think we should definitely delete after upload, but still offer SD Storage since network accessibility is scarce.
