### ISSUE TITLE
Unable to reject a capture.

### ISSUE THREAD

**Issue by nprude** [Greenstand/treetracker-android#1095]
1. Download and install build 196.
2. Register new user and take/upload pictures.
3. On the admin website, navigate to the verify page.
4. Search for the user you just created.
5. So like one of the photos you uploaded.
6. Select the reject option.
7. Hit the submit button
Expected Result
Photo rejected successfully.
Actual Result
Error message displayed letting the user know the Accept/Reject failed.
![Screenshot_20230504-174656](https://user-images.githubusercontent.com/61808960/236348217-e05c2cf3-c8f6-4d58-9284-dabc8150b005.png)

**Comment by EngrTaofeek** [comment]
@sebastiangaertner  I think this is an admin panel issue.

**Comment by EngrTaofeek** [comment]
This is an admin panel issue. Would tag respective people then close @Kpoke  @sebastiangaertner  @dadiorchen
