### ISSUE TITLE
Will there be a search feature added to the Species page?

### ISSUE THREAD

**Issue by nprude** [Greenstand/treetracker-android#1099]
I was testing the Species page and was wondering if a search feature will be added. 
**To Reproduce**
1. Launch https://test-admin.treetracker.org
2. Navigate to the Species tab.

Actual Result:
There is no search feature, but I was wondering if one would be added if the  species list becomes to long.

**Comment by EngrTaofeek** [comment]
This is an admin panel issue. Would tag respective people then close @Kpoke  @sebastiangaertner  @dadiorchen
