### ISSUE TITLE
My uploaded payment information not displayed on Payments page.

### ISSUE THREAD

**Issue by nprude** [Greenstand/treetracker-android#1100]
Log on to Tree Tracker Admin.
Go to Payments page.
Upload file successfully.

Test Result:
Information uploaded not displayed on page.
Maybe I am not putting the correct information in my csv file?
Screenshots:
![PaymentsUploadSuccess](https://github.com/Greenstand/treetracker-andro
![MyTestCSV](https://github.com/Greenstand/treetracker-android/assets/61808960/d98d257b-378b-45b7-8816-e6268780a806)
id/assets/61808960/883a3467-7f99-4c30-99c0-b95d07303184)

**Comment by EngrTaofeek** [comment]
This is an admin panel issue. Would tag respective people then close @Kpoke  @sebastiangaertner  @dadiorchen
