### ISSUE TITLE
Edit Grower page hangs up after selecting Organization and hitting save.

### ISSUE THREAD

**Issue by nprude** [Greenstand/treetracker-android#1101]
1. On the Treetracker admin page, go to the Growers page,
2. Search for and click on a grower.
3. Click on the Edit button.
4. Select an organization and click Save.

Test Result: 
Spinner keeps spinning. Hitting cancel and trying to re-enter the Edit Grower page ends with the same result.

**Screenshots**

![EditGrowerHangsUp](https://github.com/Greenstand/treetracker-android/assets/61808960/764fb89c-19f8-495d-8cef-820a7b66d65d)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 -Chrome

**Comment by EngrTaofeek** [comment]
This is an admin panel issue. Would tag respective people then close @Kpoke  @sebastiangaertner  @dadiorchen
