### ISSUE TITLE
Memory Optimisation Code

### ISSUE THREAD

**Issue by dezidaisy** [Greenstand/treetracker-android#112]
https://medium.freecodecamp.org/how-we-reduced-memory-footprint-by-50-in-our-android-app-49efa5c93ad8

**Comment by deepwinter** [comment]
@desaisameera See my comments in the PR for this, I'll need to see some memory profiling results before merging this work.

**Comment by Elforama** [comment]
@deepwinter Is this issue still needed?

**Comment by Davidezrajay** [comment]
This one seems to have been fixed on the move to Kotlin. To be evaluated again later
