### ISSUE TITLE
Add Privacy Policy

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#12]
Checkbox "I have read, understand and agree to the terms of this [privacy policy](https://www.greenstand.org/privacy-policy/)

![privacy policy screen shot](https://user-images.githubusercontent.com/25363572/32117608-7c1dbfb6-bafb-11e7-83ab-495ccd114813.png)

**Comment by Davidezrajay** [comment]
We removed the Original Sign in page and now need figure out where this privacy policy check box goes

**Comment by deepwinter** [comment]
Let me know what you want to do.

**Comment by Davidezrajay** [comment]
https://privacypolicies.com/blog/gdpr-compliance-apps/

In order to comply with this requirement, your app must provide users with certain disclosures about the information you collect, as well as a checkbox, button or other means for users to actively click and confirm their consent for you to collect their data.

**You cannot pre-select a consent checkbox or button, or assume that continued use of your app meets the GDPR’s requirement of acquiring active consent.**

**Comment by deepwinter** [comment]
Oh dammit still need the privacy policy checkbox added to the new user details fragment
