### ISSUE TITLE
Add Swahili Translation

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#122]
Update--boresha
Upload --pakia
Uploaded-imepakiwa
GPS--GPS
Accuracy --usahihi 
GPS accuracy --Usahihi wa GPS
Meters--mita
Sync-sawazisha
To sync--yakusawazisha.
Resume--endeleza 
Pause--katisha
Data-data 
About--Kuhusu
Map--ramani
Your note--maoni yako
New tree--mti mpya
Insufficient--haitoshi
Insufficient GPS accuracy-- GPS sio sahihi
Save--hifadhi. 
Information--maelekezo

The following is the translation of the information page
Kuhusu.

Tree Tracker planter app ni kifaa cha kufuatilia miti, kilichotengenezwa ili kuwawezesha watu na mashirika kupanda, kufuatilia na kulinda miti.

mpangilio wa kifaa chako unahitaji usahihi wa GPS wa (mita10).

Ili kufahamu kwa undani zaidi ni kwa jinsi gani kifaa hichi kitanufaisha mradi wako wa upandaji miti, tembelea tovuti ifuatayo.
www.Greenstand.org

kifaa hichi bado kipo kwenye matengenezo. kama una maombi yeyote au kama kifaa chako kimeshindwa kufanya kazi vizuri, toa taarifa kupitia e-mail ifuatayo.
info@greenstand.org

Treetracker(kwa majaribio)1:2:1
            awamu ya 31

**Comment by MRI1822** [comment]
[TreeTracker.xlsx](https://github.com/Greenstand/treetracker-android/files/2804628/TreeTracker.xlsx)

**Comment by deepwinter** [comment]
Can this be closed?
