### ISSUE TITLE
Keep Master Branch in sync with Production App

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#124]
After we get this next version up, the master branch should be reserved for the live app. 
All work should take place in the Dev branch

**Comment by deepwinter** [comment]
i think we want to just tag releases rather than having a separate branch for production

what are you hoping to achieve with this?

**Comment by Davidezrajay** [comment]
The goal is to know exactly what is in the play store. 

Where is the tag placed?

**Comment by deepwinter** [comment]
Tagging is used to specify a specific release.  For some reason we didn't do that last time we pushed something out.  I think it's bcaddb3e9c9872eb9dd6664d831f954824519b9b but it's true, we did not tag it.

**Comment by Davidezrajay** [comment]
Cool.
Closing this issues and adding "Tag Release" to issue #123
