### ISSUE TITLE
Change The "Sign in Page" 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#125]
1. Remove password requirement - this is where people are getting stuck
2. Require 
- Name
- And Phone number or Email

If, the phone has internet and no user data exists then require sign up.

Otherwise, just allow the user to take images and upload. (This works as long as the phone is identifiable and there has been a complete sign up from that phone in the past.)

**Comment by deepwinter** [comment]
See #104 for solution
