### ISSUE TITLE
Interrupting upload can cause duplicate tree entry

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#127]
When interrupting an upload of 1500 trees by turning on Airplane mode, one tree was inserted 2 times into the web database.

**Comment by Davidezrajay** [comment]
https://github.com/Greenstand/treetracker-mobile-api/issues/9 seems related

**Comment by Elforama** [comment]
Talked with @deepwinter and decided that each tree should be associated with a UUID in the database. This UUID will be sent to the "trees/create" endpoint as an additional value in the body
