### ISSUE TITLE
After Login UX Flow

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#132]
After Login, the app brings up the camera. 
It should go to map first.

**Comment by deepwinter** [comment]
Hmm.  Well you only get to the login page by clicking '+' from the map.  So it may be confusing to go back to the map?

**Comment by deepwinter** [comment]
Keep in mind that the Login is going to pop up every 2 hours or so, when you clicking '+' from the map to add a tree.  If go back to the map, it's not clear the '+' really means to add a tree.

**Comment by Davidezrajay** [comment]
> Hmm. Well you only get to the login page by clicking '+' from the map. So it may be confusing to go back to the map?

No... you got to the Login Page by "changing user" or when it forces you to do so.

**Comment by deepwinter** [comment]
It generally forces you do so when you click '+' from map.  The 'change user' flow is going to be much more rare.  In that case going to map should happen, but I don't think it should when you click '+' from map.

**Comment by Davidezrajay** [comment]
Consider Map Page home page. After Login, app should show 'home page'

**Comment by Davidezrajay** [comment]
Current operations from timed out user, or opening app for first time: Open App -> Map View -> '+' -> Login -> Camera -> Photo Preview/Save -> Map ->
