### ISSUE TITLE
User photo is upside down

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#136]
Using the selfie camera returns an upsidedown user photo.  Rotate photos 180 degrees before saving when they come from the self camera.

**Comment by Davidezrajay** [comment]
Also seems to crop out most of the photo

**Comment by deepwinter** [comment]
@Davidezrajay I think it's just that the display window for the photo is square while the full photo is a rectangle.  The complete photo is saved to our cloud storage regardless.

**Comment by sebastiangaertner** [comment]
Login button does not show anymore. Keyboard stuck on top and does not go away.

**Comment by deepwinter** [comment]
@sebastiangaertner can you post screenshots of the problem you describe?  I see the login button in that image.

**Comment by sebastiangaertner** [comment]
I managed to log in with built 35. but not seeing my trees that are registered under that user.and the picture that appears on top right side of the map is upside down.

**Comment by deepwinter** [comment]
@sebastiangaertner You will no longer see trees sync down to the app from the server.  This is because displaying those trees on the mobile app needs extra engineering to not brutally slow the device, so we cannot support thousands of trees on mobile at this time.  They are synced and permanently stored in the cloud.  However this is a different issue from this ticket.

Upsidedown user image is now resolved.  Tested on Samsung Galaxy J36v
