### ISSUE TITLE
Syncing not working

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#138]
Logged in with Telephone number. Took image of tree and checked in Data. To Sync = 1 
not syncing. Am certainly on a network (wireless) that is faster than the usual phone 3G connection.

**Comment by deepwinter** [comment]
Sync was broken on the test infrastructure due to a missing database migration.   Please tag in the future with which infrastructure you are testing (dev, test, or production).  Thanks!  This is resolved.
