### ISSUE TITLE
Build Version 36 closes down when pressing "start planting button"

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#142]
Samsung S7 . Beta/Treetracker Debug Build Version 36. Can not get passed the "start planting button"

**Comment by deepwinter** [comment]
Do you have a phone number or email in place, and a picture?

And what phone or email are you using?

**Comment by deepwinter** [comment]
Oh, also please delete and reinstall the test application.

**Comment by deepwinter** [comment]
What phone number are you getting a crash from?  I need all the specifics so I can see if I can recreate the issue!

**Comment by sebastiangaertner** [comment]
0784589075 
--
Sent from myMail for Android Tuesday, 18 September 2018, 10:19PM +03:00 from zaven  notifications@github.com :
