### ISSUE TITLE
Privacy Policy Link Broken

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#145]
The link on sign up page should bring up a privacy policy

**Comment by deepwinter** [comment]
I copied that code verbatim from the previous version... it doesn't bring up the policy ??

**Comment by Davidezrajay** [comment]
Box works fine but the link do not do anything. I tagged this issues for the next release

**Comment by deepwinter** [comment]
https://www.greenstand.org/assets/GreenStand-Privacy-Policy.pdf is dead on the website

**Comment by Davidezrajay** [comment]
Set to 
https://www.greenstand.org/wiki/privacy-policy
