### ISSUE TITLE
GPS Searching/ loading wheel

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#159]
When people turn the app on while inside a building, they think it is broken. 

There needs to be something to show that the app is searching for the GPS signal.

**Comment by Davidezrajay** [comment]
https://github.com/Greenstand/treetracker-android/blob/master/Design/App_Screenshots/Map%201.2.3%20(45).png

**Comment by amrutamaliux** [comment]
We already have two design decisions made in the current wireframes. When the app finds GPS signal, it shows the related text in green and when it can't find the signal, the text turns red. We can try something on similar lines when GPS signal search is in process. E.g. the text "Searching for signal" turns blue with a simple dot animation. Or else I can look for some animated icons too but considering some of the users don't have strong internet connection, it's better to keep it light.

**Comment by Davidezrajay** [comment]
GPS representation/user flow: another thought has been to move the 'GPS accuracy feature that blocks the camera' to the actual camera preview page...

**Comment by peacengn** [comment]
In the new design, we have a filter with images showing the user that they need to go outside. Once they're outside, the filter goes away.

**Comment by Davidezrajay** [comment]
#172
