### ISSUE TITLE
Option to delete bad tree images.

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#160]
There is no way to delete a bad image. We might consider this option. People have asked for it. 

Adding another button can create a lot of issues with our users. We have intentionally left it as it is likely low-tech-literacy-users will delete all photos instead of saving. It is better to have bad images then no data at all.

Before you code this: identify the user interface (where that button can go/what it looks like), and the complete functionality to this button, will it bring up the camera again or take you back to the map?

**Comment by natalieschulz** [comment]
![camera requirements](https://user-images.githubusercontent.com/9558167/51933046-4c706d80-23b5-11e9-9b37-64d81b1c5e02.png)
![save_tree requirements](https://user-images.githubusercontent.com/9558167/51933049-4c706d80-23b5-11e9-8703-53e2c0b5d86b.png)

**Comment by natalieschulz** [comment]
Let me know if you want svg files for the shapes, couldn't upload them to github

**Comment by Davidezrajay** [comment]
The "Add a Tree" and the "Save Tree" at the top with the arrow appears to be bringing the user to the page which is the page the user is on.

**Comment by MRI1822** [comment]
Thanks @Davidezrajay I was thinking the same and thanks @natalieschulz for clearing it up

**Comment by natalieschulz** [comment]
![save_tree requirements](https://user-images.githubusercontent.com/9558167/51936946-31eec200-23be-11e9-8eb7-375223af88c6.png)
![camera requirements](https://user-images.githubusercontent.com/9558167/51936947-31eec200-23be-11e9-8b82-a8a823ce0951.png)

**Comment by natalieschulz** [comment]
![save tree copy](https://user-images.githubusercontent.com/9558167/51936993-4df26380-23be-11e9-8df5-7b7f831045a1.png)
![add tree copy](https://user-images.githubusercontent.com/9558167/51936995-4e8afa00-23be-11e9-8f5d-2115826e508d.png)

**Comment by natalieschulz** [comment]
Sorry just talked to peace and we've created new screens with the trash icon. I've uploaded the svg files to the slack thread as well, let me know if you have any trouble finding them! and thank you!

**Comment by Peacenux** [comment]
I've noticed that this function would be for release 1.2.5, is it now for 1.2.4?

**Comment by Davidezrajay** [comment]
We will come back to this... Ice box
