### ISSUE TITLE
Review text

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#170]
1.  "Show us who you are..." this is too strong. 
Maybe "Add Planter Photo" or "Planter Photo"

2. "Provide your details to continue"
Can this be deleted?

**Comment by peacengn** [comment]
In our new design, we have "Take a Selfie" for the planters to take a self-photo and just a standard "login" and "signup" button to continue with colored button.

**Comment by Elforama** [comment]
@Davidezrajay Is this covered in the new login flow design? If so, this can be closed.

**Comment by Davidezrajay** [comment]
Thanks @Elforama closed this
![LOGIN_SIGNUP_SPECS](https://user-images.githubusercontent.com/25363572/55755273-137af780-59fb-11e9-8218-3aa49c228f84.png)
