### ISSUE TITLE
Main Map Page Wire Frame

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#174]
We need new wireframes as the old wireframes are no longer valid.

**Comment by Davidezrajay** [comment]
from @snacks "There are quite a lot of things going on at the bottom of the screen, this should be parsed out a bit. ie: maybe the text for gps accuracy should be stacked on the side above the Google logo."
Closed #163 As duplicate

**Comment by Peacenux** [comment]
![android - map 1](https://user-images.githubusercontent.com/20362715/49252072-e9c01d00-f3d7-11e8-853f-36a7d1636a66.png)

**Comment by Davidezrajay** [comment]
Thoughts... 
The tree button should dominate... as the primary thing on the page and easy to push. Target users are pressing it hundreds of times a day. It should also be in line with the save button on the save tree screen.

Do we need the map button on the button? 
 
It seems there are two menu buttons?

**Comment by Davidezrajay** [comment]
It appears people don't know that the button means to take a picture of a tree. We have since added the text "Add Tree" but that still has on meaning to someone who can't read. 

I like the "add tree" Icon and text combination in the wireframe above. Could we just make that larger and prominent?

**Comment by peacengn** [comment]
In the new design we have a camera button that stands out in the map page.
