### ISSUE TITLE
Display app version in app

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#18]
Read app version and build from manifest, and display in the app for bug reporting and support.

**Comment by deepwinter** [comment]
@Surbhi79 completed this task.

**Comment by deepwinter** [comment]
This got removed in error somehow.

**Comment by Elforama** [comment]
Where should the app version show?

**Comment by deepwinter** [comment]
Check out the live production app.  I believe it is on the data page.  The feature regressed in the current code.
