### ISSUE TITLE
Sign In Pages Wire Frame

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#180]
There are a few issues with the current sign-in process. 

Some buttons are below the bottom of the page and hard to see. 
The "done" button on the keyboard is hard to spot..
Is not clear that user is taking pictures of a person and not a tree

https://github.com/Greenstand/treetracker-android/blob/master/Design/App_Screenshots/Add%20User%20page%20with%20keyboad%201.2.3%20(45).png

https://github.com/Greenstand/treetracker-android/blob/master/Design/App_Screenshots/Add%20user%20page%20(no%20image)%201.2.3%20(45).png

**Comment by peacengn** [comment]
In the current state (1.2.3), it can be easily changed in code.

Our new design 1.2.4 will have margins and padding to fix this issue.

**Comment by Davidezrajay** [comment]
Thanks, @peacengn Amazing work! You are awesome!
