### ISSUE TITLE
Wireframes: Login, sign up, profile picture

### ISSUE THREAD

**Issue by ghost** [Greenstand/treetracker-android#185]
**Final designs: colors, text, images, fonts, etc will be added in final draft.** 

![android - login](https://user-images.githubusercontent.com/20362715/48965553-80be4c80-ef74-11e8-8e5e-666f72bd5c7c.png)

![android - sign up 1](https://user-images.githubusercontent.com/20362715/48966500-a7d24980-ef87-11e8-8aa6-f0ce21840f33.png)

![android - profile picture](https://user-images.githubusercontent.com/20362715/48965554-80be4c80-ef74-11e8-89fd-476ea99faa6d.png)

**Comment by Peacenux** [comment]
Login Page: Current users only need to enter their phone number or email address. 

Sign Up Page: New users must create an account and enter: full name, organization, phone number, email

Profile Picture Page: New user takes a selfie to save as their original picture/security identification purposes.

**Comment by natalieschulz** [comment]
Are we still using email address? I thought that might have been a limitation since many users don't have one

**Comment by Davidezrajay** [comment]
The current app allows for email or phone number. 
It creates a master user at first login. 

Each login expires after two hours and forces users to add the same information again. Cumberson but it seems to work

https://github.com/Greenstand/treetracker-android/blob/master/Design/App_Screenshots/Add%20user%20page%20(no%20image)%201.2.3%20(45).png

**Comment by peacengn** [comment]
Our new design already addresses this issue. 

New user login: name, phone number, email (optional), organization (optional)
Existing user login: phone number, email (optional)

**Comment by Davidezrajay** [comment]
Updates have been loaded into Android design 
![Screenshot (169)](https://user-images.githubusercontent.com/25363572/55754688-bf234800-59f9-11e9-9558-f60903a8da89.png)
