### ISSUE TITLE
App can't be installed.

### ISSUE THREAD

**Issue by AndroidDev77** [Greenstand/treetracker-android#194]
Tree Tracker App can't be installed. I get error code 910

I'm on Android Version 8.0.0

**Comment by Davidezrajay** [comment]
Are you installing it from the play store?

**Comment by AndroidDev77** [comment]
Yes

**Comment by Davidezrajay** [comment]
Thanks, looking into it now

**Comment by LaviniaDragunoi** [comment]
This is odd, I have Android 8.0. 0 and it's perfectly working. I just installed the app now from google play. Do you have already other version of the app on your device? I mean the debug version of the app?

**Comment by Davidezrajay** [comment]
@AndroidDev77 Thank you for opening this issue. It is really good to know about these things. 
Please let us know what you find on this
https://android.stackexchange.com/questions/204469/why-is-play-store-showing-cant-install-app-error-code-910

**Comment by AndroidDev77** [comment]
@laviniadragunoi That was it, I had to remove the debug version to install it from the play store.
