### ISSUE TITLE
Open numeric keypad for phone number entry

### ISSUE THREAD

**Issue by natalieschulz** [Greenstand/treetracker-android#205]
From the user testing videos uploaded to Slack, the phone number entry part of the Login/Sign Up screens seems to take users a significant amount of time, in part because the numbers are so small.
As a result, we want to open a numbers-only keyboard when users are entering their phone number on the Login and Sign Up screens. 

![google-keyboard-tips-numberpad-100671904-large idge](https://user-images.githubusercontent.com/9558167/50022273-66cec300-ff90-11e8-92f7-c7e009f10a89.jpg)

**Comment by LaviniaDragunoi** [comment]
Is not only numerical because login is with phone / email. If it will be changed to register only with the phone number then it will be a super great idea. Excluding email could be a good idea to make easier the registration more efficient for users.

**Comment by natalieschulz** [comment]
@LaviniaDragunoi Oh good point, I didn't realize they were both in the same field. 
@Davidezrajay Can we limit login to phone number only or should we wait on this until/if we break it into 2 fields?

**Comment by Davidezrajay** [comment]
I defer to @peacenux :)
 
Although, ideally, we keep the option for an email as well.  I like the two fields idea, albeit more work, and think the keyboard is a great idea and will certainly help.

**Comment by LaviniaDragunoi** [comment]
Is not to much work @Davidezrajay. I want to implement a databinding feature in the code that will make everything easier and will help to avoid errors. I think the same, that keeping both in separated fields will be the best solution. And of course with keyboard special for each inputText type

**Comment by sebastiangaertner** [comment]
We should def. keep the email authentication. Once logged in via email the user should stay logged in. Phone Number users get logged out after some time. That would make sense since people with email address are most likely phone owners. If they give their phone away to other planters they can still log out if need be.

**Comment by Elforama** [comment]
@Davidezrajay Is this issue covered in the new signup redesign? If so can this ticket be closed?

**Comment by LaviniaDragunoi** [comment]
@elforama, in the new design the phone number is separated by the email address and the db is checked either by phone or e-mail. The phone editText has only numerical keypad. So the issue in my point of view could be closed.

**Comment by sebastiangaertner** [comment]
We do need a plus + signs for country code. Is that included? Currently not working 
--
Sent from myMail for Android Saturday, 06 April 2019, 03:07PM +03:00 from Lavinia Dragunoi  notifications@github.com :

**Comment by Davidezrajay** [comment]
Well done! This is wonderful!
