### ISSUE TITLE
Add Blur Detection to App

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#207]
This code should be able to flag the blurred image for the planter.

https://github.com/DominionSoftware/BrennansFocusMetric
Requierments: 
- Implement code
- Design flag feature for blury images (could be an 'X') 
- Test on multiple devices

Test: 
- Planter takes image
If the image is blurred, image if flagged and the user has an option to retake image or to continue to save the image. 
- If the image is not blurred, the image is not flagged. 
- If phone consistently flags images as blurred, the operation of the application is not prevented or slowed down.

**Comment by Elforama** [comment]
V1 for this is complete. Marking this as done.
