### ISSUE TITLE
UX for Blur Detection on Save Image Preview Page

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#208]
Ticket [#207 Add Blur Detection to App](https://github.com/Greenstand/treetracker-android/issues/207) requires a warning to the user, such as an 'X' on the image, if the image is detected as blurred. 

To be designed on the [Save Image Preview Page](https://drive.google.com/a/greenstand.org/file/d/1TmX-PdLrtD0NgY_Aff7Z2BybDDpOIaFC/view?usp=sharing)

Test: 

- If a blurred image is detected, the user is warned and can quickly decide if the image requires a retake. 
- The user is able to retake photo OR user is able to save the photo and continue. 
- If the blur detection code is not working properly on a device, it allows the user to continue without annoyance.

**Comment by peacengn** [comment]
First screen: _If the blur feature is **not** working_: this would be helpful if the app isn't able to detect that the image is in fact blurry. The user has a choice to delete a bad photo when they decide to via the trash button. The users can still move forward by selecting "save" for a good photo. 

Second screen: _If the blur feature **is** working_: the user is prompt with a dialog box when the app detects their image is blurry. Users who select "ok" will be led back to the camera to retake a photo of their tree. The user can deny the prompt by selecting the "cancel" option if they choose to.

![New_Tree_Confirm](https://user-images.githubusercontent.com/20362715/55196927-27f30080-516e-11e9-8a16-dbd1320b6657.png)

**Comment by Davidezrajay** [comment]
@peacengn , I like how you are thinking. The **user must be able to completely bypass the warning and just press save**. This adds a second step, as the user has to move thier finger and press ok first. 

What about something like a red question mark and a back button or retake button?

**Comment by peacengn** [comment]
At your request, the second step is removed. Here, the users can bypass the warning then proceed to select "save". Users will still be able to use the back button at the top and delete their photo if they choose to. 

![New Tree-2](https://user-images.githubusercontent.com/20362715/55263701-22112400-522f-11e9-8de4-e6a02d47b5f8.png)

**Comment by Davidezrajay** [comment]
@peacengn can we remove the delete option here and highlight a back button.

**Comment by peacengn** [comment]
@Davidezrajay can you explain what you mean by highlighting a back button?

**Comment by Davidezrajay** [comment]
https://docs.google.com/drawings/d/1CkkffY48rDrCJ3hLVtdVa4diHrFUj5D3oAzlLWuU_Ec/edit

**Comment by Elforama** [comment]
Is this considered complete? @Davidezrajay @deepwinter
