### ISSUE TITLE
UX - Evaluate time required per tree entry

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#210]
For planters to break out of level 2 poverty to level 3 and reach 16USD a day they need to verify 500 trees a day - that is a little more than a tree a minute and doesn't include walking from tree to tree.  

Verification/taking a picture needs to be really fast.

**Comment by Elforama** [comment]
@Davidezrajay What actions should be taken in the app for this?

**Comment by Davidezrajay** [comment]
Thanks @Elforama, I've moved this to the icebox until it is needed. We just need to evaluate how to make the process of logging trees faster as users will be tracking large numbers of trees in a day.
