### ISSUE TITLE
Evaluate Sync Failure

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#214]
In previous versions of the app, users were able to sync from areas of extremely poor network. Now we have multiple reports of users unable to sync. @sam (our main field guy) says that the app will never sync on an 'edge network.' 

These users are still able to send photos and videos over whats app from these same locations. 

Possible issues include user error: such as phone settings, data services not paid for, only trying at times without any network at all, etc. 

![Start Syncing](https://user-images.githubusercontent.com/25363572/51492096-0edc6680-1d5d-11e9-9ce9-17801db2f497.jpg)

![photo-2019-01-20-02-07-09](https://user-images.githubusercontent.com/25363572/51492119-23b8fa00-1d5d-11e9-9e4c-b8c1debc8a91.jpg)

**Comment by deepwinter** [comment]
2 problems worth looking into
1) Get the 'sequence id' concept implemented to detect duplicate uploads
2) The location of the datacenter / cloud storage could be incurring too much delay over Edge

**Comment by Elforama** [comment]
Is this still an issue?
