### ISSUE TITLE
Create Style

### ISSUE THREAD

**Issue by LaviniaDragunoi** [Greenstand/treetracker-android#217]
Create InactiveButtonStyle   , ActiveButtonStyle, TextTitleStyle, TestBodyStye, InactiveTextStyle.  
Add a new color palette.  Like UxTeam suggested in the attached images
![style guide](https://user-images.githubusercontent.com/36914492/51985231-165ee680-24a6-11e9-8f42-bff0fea69e38.png)

**Comment by Peacenux** [comment]
Only the first style guide for reference is needed

**Comment by LaviniaDragunoi** [comment]
Thanks! I've delete it. It's ok now?

**Comment by LaviniaDragunoi** [comment]
Solved with PR #221
