### ISSUE TITLE
Sign Up "account" function

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#225]
An "account", in this case, would be a previously used phone number or email stored on the device. 
If the phone recognizes a phone number or email, it skips the page to enter the full name and organization text boxes and goes directly to the selfi-page. 

As per this user flow. 

![1 2 4-block](https://user-images.githubusercontent.com/25363572/53561158-8fc81400-3afa-11e9-8b35-2f3828ba10c0.png)

**Comment by sebastiangaertner** [comment]
Yes. This is important.
