### ISSUE TITLE
Tree Height Feature

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#226]
This feature is to support another organization and will be released on the play store as a different version of the app.

It allows the user to add a hight of the tree.
![Version 2](https://user-images.githubusercontent.com/25363572/54081846-3610d800-42b8-11e9-9c24-93ad9aec88c4.png)

Please send tree height (as color) in an attributes hash as part of the newTree api call.  The attributes attribute of the tree json should look like

attributes: {
  height_color: 'blue',
  flavor_id: 'app flavor',
  app_version: 'app version id',
  app_build: 'app build id'
}

**Comment by Elforama** [comment]
I can take on this issue if no one else is. Although, I'd suggest that we make this screen hidden behind a feature flag. Either we switch it on/off manually depending on who the build is for, or we make flavors for our android app. A normal flavor (where the flag is false) and a flavor for that org (where the flag is true). That would allow us to easily build 1 or 2 different versions of the app. They can even have their own branding if we want.

**Comment by Davidezrajay** [comment]
@Elforama This would be wonderful if you take this one. Flavors seem correct. Thanks for pointing this out.

**Comment by Davidezrajay** [comment]
Color Values ![image005](https://user-images.githubusercontent.com/25363572/54385006-766eae00-464a-11e9-96b2-27ee3c1f13a9.jpg)

**Comment by deepwinter** [comment]
@Elforama Updated the description with the attributes attribute json spec.

**Comment by peacengn** [comment]
I like the idea of having a graphic for tree height reference (human not necessary). This could help users understand how the feature works within the app for our intended audience. The users are currently using physical sticks to carry with them in the field, but in cases like if the users misplace the sticks, they can still use app as reference.
