### ISSUE TITLE
Remove Retake Photo Button

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#23]
Current operation: after the user has taken a photo, this brings up a frozen camera screen.
Delete it?

**Comment by deepwinter** [comment]
@Davidezrajay This seems to be working on my device, need you to demonstrate this not working on a device so it can be fixed.

**Comment by Davidezrajay** [comment]
A future issue
Samsung-SM-J120A does not have the "retake Photo button" but allows the second photo without changing GPS accuracy. Should reset GPS at time of photo to prevent scamming.
