### ISSUE TITLE
Can't change user

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#232]
If you to change users it will not allow you to continue after entering details on the details page.

**Comment by Elforama** [comment]
This bug has to do with how we handle navigation in the app. Once we complete the user identification screen, we actually go back to the map screen which then deletes the user data before we go to the user details screen. The user details screen does not allow us to continue due to the userIdentifier being deleted on the map screen.

**Comment by deepwinter** [comment]
@Elforama This is a priority issue.

**Comment by deepwinter** [comment]
Fixed in PR, will be deployed to test.
