### ISSUE TITLE
Setup google-services.json correctly for all builds and flavors

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#242]

**Comment by deepwinter** [comment]
We are currently using the same google-services.json for all builds, and I think this is giving us install conflicts in production.

**Comment by arunbakt** [comment]
I have created separate google-services.json for different flavors such as justdiggit and organization. I saw recommended way is to create separate projects for each flavor. @deepwinter /@elforama, could you please see if the ones I have created looks fine? They are under the account owned by @Elforama .
