### ISSUE TITLE
Can not enter Country code on Telephone Number. 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#245]
Can not enter Valid Telephone number with country code +255 or +1 or any other. This should be possible since it will be hard to determine that later. Any "Country code by area planted" or "country code by Network" used would be based on an assumption.

**Comment by Davidezrajay** [comment]
@sebastiangaertner Closing this for now. It may pop up again but will not be dealt with until we have @peacengn work fully integrated.
