### ISSUE TITLE
Notify user when location is disabled

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#25]
On Android location can be disabled even though the user has granted permission to the app to use location.  We need to notify the user when they do not have location enabled, so that they can enable it.

**Comment by Davidezrajay** [comment]
![screenshot_20180104-201839](https://user-images.githubusercontent.com/25363572/34596624-cd9c2c6a-f18d-11e7-8ed3-e0d54a5081ff.png)
It asks after photo is taken. Should ask at time of saving location.

**Comment by Surbhi79** [comment]
Close issue.
