### ISSUE TITLE
Logo Design For Tree Tracker

### ISSUE THREAD

**Issue by zularizal** [Greenstand/treetracker-android#254]
Hi @deepwinter , I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by Davidezrajay** [comment]
Hello @zularizal, thanks for your offer. Feel free to submit here, or join us on slack

**Comment by Davidezrajay** [comment]
@zularizal, Feel free to open another ticket and submit your log here, you may also consider joining the team on Slack and tuning into what we already have going on. 
https://docs.google.com/forms/d/e/1FAIpQLSe61HDJKVH16vtTxhXpbwCH-wTVN1e6XoVU1riWjJ-ne5SIiA/viewform I'm closing this issue for now
