### ISSUE TITLE
Extend-phone/email fiel

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#264]
Amazing work! 

User has to click on the actual text to bring up the keyboard. The first time I used it, I clicked the left side of the text field about 30 times before I managed to get the keyboard. 

It seems like the field needs to be extended so that if one clicks on the left side it brings up the keyboard. 

![Screenshot_20190425-145202](https://user-images.githubusercontent.com/25363572/56773280-f0c24000-6769-11e9-884b-e86216901fdc.png)

**Comment by deepwinter** [comment]
Ah, I'm glad you figured out what was happening here.  It was really puzzling me, I though my phone was slow or something.
