### ISSUE TITLE
White label: Just Dig It - Text/color code

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#268]
Text: Din next lt pro

Just Digit Color Codes: 

- Green:
   #7AC144
   RGB: 122,193, 68

- Orange (to be used only a little bit):
    #ED6F2E
    RGB: 237, 111, 46

- White:
    #FAF9F4
    RGB: 250, 249, 244

- Black:
    #262626
    RGB 38, 38, 38

One check justdiggit.org website for the overall style

**Comment by Elforama** [comment]
We'll need to know which colors in the current design are to be replaced with white label colors.
