### ISSUE TITLE
White Label: Just Dig It - Logo

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#269]
Full set of images here: 
https://drive.google.com/drive/folders/1bqCllV_SMRsJbOcu6tNT-QPAz4qAdabG?usp=sharing
The logo appears on the following pages.

[ ] Splash Screen (Do we even want this screen at all? 
[ ] Sign in page
[ ] About page
[ ] Tree Data page

**Comment by Elforama** [comment]
What's our logo? Is it the tree, or the image of two leaves?

**Comment by deepwinter** [comment]
'Our' logo for the purposes of the App is the 2 leaves.

**Comment by deepwinter** [comment]
Just dig it logo is the shovel thing
