### ISSUE TITLE
Replace Generic Privacy Policy Text

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#275]
Link: https://www.greenstand.org/privacypolicy

GreenStand - Privacy Policy

At GreenStand we have absolute respect for your privacy and will continue to do everything within our power to protect it.  We hereby disclose GreenStand’s privacy practices concerning the data we collect.

How We Handle Data:

Our primary goals are to use data to create a greener earth and offer an option for economic opportunity in areas of extreme poverty. We believe that the scientific and project related data we collect (that is not private by nature) should be freely available to the public. Unless otherwise authorized we will not disclose sensitive user information, such as contact information. Our primary data collection is focused around scientific research and creating a transparent system to collect field data related to the survival processes of trees as well as any information related to the systematic harvesting of tree related products. This information includes planter geo-tagged, time-stamped photos and other user entered data.  

By using our services, you are agreeing to allow us to use your environmentally related information and make it publicly accessible via websites.  User’s first name and/or organization name may be displayed with the corresponding tree data. With prior consent, other user related information may be displayed. Upon request all user data may be hidden from public view. Phone numbers and/or email addresses may be used by GreenStand to contact planters, but will not be shared with third parties without prior consent.

Project Related/Scientific Data:

GreenStand upholds an open scientific data policy and intends to make any scientific finding, that may positively affect the environment and/or social welfare, freely available. Using data we receive through user inputs on our mobile applications, website and database systems, we intended to identify problems, solutions and trends in environmental/social health.  By using our services and software, you are thereby agreeing to allow us to publicly display project related data and scientific findings. In the event that data collected with this software is sensitive, please contact us at Info@greenstand.org so that we may act accordingly.

How We Collect Data:

Mobile Applications:

Photos: time-stamped, Geo-tagged.

User entered information: name, email address, organization name, phone number, field notes.

App settings for users

Application analytics: software crash reports, phone make and model.

Website Application: Database entries, general analytics.

Donor supplied information

User Data We Collect:

Information relating to individual users or organizations will not be disclosed without prior consent.  We are handling all user related data (full name, phone numbers, email) securely using modern cryptography. Planter’s full names and contact information will never be shared without prior consent.

Personal Information: On our tree tracker app we require a name, and email, and optionally a phone number and an organization name. All personal data is stored in a secure database.

Mobile App users: Our mobile apps collect the following personal information: User entered information: name, email address, organization name, phone number.

Donor information: When you make a donation we collect information that is used solely for accounting, tax reporting and donation processing purposes. This information is guarded with utmost care and will not be sold, shared or traded with any other entity.  We do abide by IRS requirement to disclose limited information that is mandated to be available on public taxes records. Donor information may also be disclosed at the donor's request. We collect the following donor information: name, address, amount of donation, any other personal information given to us.

User Photos:  

GreenStand’s tree tracking program runs on the collection of time-stamped, geotagged photos. This information is stored in a secure database from which it is displayed in the form of a tree map. We also use this information to generate statistics related to tree planting. We are only interested in tree-related photos, please don’t send us anything else. With the proper use of this system, all photo taken will relate to environmental data and GreenStand does not consider or treat uploaded photos as “user data.” By using our mobile application you are agreeing to allow us to use your photos.

Changes to the Policy

It is our intent to hold the principles of this policy, but we do understand there may be a need to change it from time to time. Changes will be posted on our website as soon as possible.

© 2019 GreenStand (registered 501(c)3 nonprofit. EIN: 47-3150283 ). Info@greenstand.org
Privacy Policy

**Comment by Elforama** [comment]
The terms of service screen has the following structure/format:

Big paragraph
1. Terms of service
2. Privacy Policy
3. Cookies Use

**Comment by deepwinter** [comment]
Note: The current design references 'cookie use' but since this is a mobile application, and not a web application, cookies are not used.

**Comment by deepwinter** [comment]
@Davidezrajay The above text does not include terms and conditions

@Elforama In order to push this out to production, we'll have to hack in the privacy policy for now.  There are no cookies for this mobile app, so that is out.  I have started hacking this in here:

https://github.com/deepwinter/treetracker-android/tree/privacy_policy

2 layout bugs need to resolved then it's probably 'good enough' for now.  
1) Text is not nicely formatted in the privacy policy body
2) The accept button doesn't wind up at the bottom of the scroll view after clicking 'Show Details' .

**Comment by deepwinter** [comment]
I think it's too confusing to have the Accept button hidden.  One of the things still working with how I had it hacked in was displaying the Accept button at the bottom of the screen before unfolding the whole terms and conditions.  If we hide the accept button, illiterate users will not necessarily scroll to find it.

**Comment by Elforama** [comment]
I can make the accept button stick to the bottom and have only the text scroll.

**Comment by deepwinter** [comment]
That would be superb.
