### ISSUE TITLE
Tree map lags when there are too many trees

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#277]
In dev build, long press the 'add tree' button. This will add 500 trees. Wait for them to load, then try moving the map. You will notice a lot of lag.

**Comment by arunbakt** [comment]
I don't notice any lag in my device or in the emulator when adding 500 trees.  Could this be because of some log levels when you saw this lag happen?

I am closing this bug, please re-open if you think this is still a problem.
