### ISSUE TITLE
Streamline color naming

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#285]
These color names are to vague, let's make it more specific:

<color name="colorPrimary">#f5f5f5</color>
    <color name="colorPrimaryDark">#000000</color>
    <color name="colorAccent">#1B5E20</color>
    <color name="white">#FFFFFF</color>
    <color name="black">#000000</color>
    <color name="red">#FF0000</color>
    <color name="link_color">#1B5E20</color>

**Comment by arunbakt** [comment]
@Elforama , when you have time, could you please elaborate? If this is not relevant anymore, I will close it. Let me know.
