### ISSUE TITLE
Create white labeling workflow

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#288]
This issue requires our first white label app to be completely finished. Once we know everything that has to be done we should document the steps for future white labels. These docs should be in the project wiki for easy access.

**Comment by arunbakt** [comment]
What is a white label app @Elforama?

**Comment by Elforama** [comment]
It's when you make anther version of the app for another organization. You'd typically change the name, colors, some text, etc..

This isn't high priority, but something we should eventually do.

**Comment by Elforama** [comment]
We are moving forward with an org flavor of the app that removes the need for white labels.
