### ISSUE TITLE
Use JustDigIt as default organization for JustDigIt flavor

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#291]

**Comment by Elforama** [comment]
Can you please provide details for this issue.

**Comment by deepwinter** [comment]
In the 'Sign Up' fragment, there is a field for 'organization' .  For the JustDigIt flavor, the text should read 'JustDigIt' by default.  I.e. it should be pre-filled.  There should be no pre-fill for the Greenstand flavor.
