### ISSUE TITLE
Create 'update mode' for Greenstand flavor

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#292]
In the Greenstand flavor only, we need to have a mechanism for putting the app in 'update mode,' which should send an additional attribute with each tree (stored in attributes table is fine).  The field is called 'update,' the value can be the string 'true,' integer 1, or boolean, whatever is easiest to send over using our existing attributes JSON.

User needs to be able to enter update mode, and exit update mode.  This should probably happen via a menu item, but we are open to other iteas.

The additional value is only sent the app is in update mode.

When the app is in update mode, also display text in the header of the map indicating this is a tree update.

This is a work around to allow Sarah to perform tree updates and have the information passed along to our database that these are updates, and not new trees.

Consider including a timeout for update mode, so that phones in update mode aren't later used to add new trees erroneously.

**Comment by Elforama** [comment]
This needs some kind of design and UX flow.

**Comment by deepwinter** [comment]
True that...

**Comment by deepwinter** [comment]
Open to ideas here... the fact is this bit of functionality needs to be in production ASAP, so I'm not feeling there is time for a real flow/UX iteration.   It's a workaround feature for a special use case, not for generic users.

**Comment by sebastiangaertner** [comment]
i like "When the app is in update mode, also display text in the header of the map indicating this is a tree update." for sure. This will be clear enough.

**Comment by sebastiangaertner** [comment]
If we can get that feature implemented for the version used in the Kilimanjaro Project then there accumulate great data to see how far off the GPS location we are. That will be vital to know.

**Comment by Elforama** [comment]
I'm wondering if a simple solution would be to provide a second button on the Add Tree screen. That button can be called "update". By pressing it instead of save, it will set the update flag as mentioned above.

**Comment by deepwinter** [comment]
We considered that, but the issue is that most users will never use 'update' at this time.. it's only for a specific use case.  So it would be better if the functionality was more hidden.  Remember that we also have folks who are not particularly literate using the app, and they will be sure to hit both buttons without a clear intention at times if given the option in the UI.

**Comment by Elforama** [comment]
Good point. In that case I will go with the menu option and work some kind of UI out.

**Comment by deepwinter** [comment]
Great!  Thank you!!

**Comment by Davidezrajay** [comment]
Skip the update button. We tried that before. Once we have enough raw data we will be able to figure out what is new and what is updated. Kilimanjaro project is already updating its trees with the current app.

![Screen Shot 2013-06-07 at 6 44 12 PM (1) copy](https://user-images.githubusercontent.com/25363572/57729079-c5809180-7641-11e9-89fd-e12e936de5a5.jpg)

**Comment by deepwinter** [comment]
This ticket has been cancelled.
