### ISSUE TITLE
Kisiki Hai splash Screens resized

### ISSUE THREAD

**Issue by AndrewKerr47** [Greenstand/treetracker-android#298]
Updated Kisiki Hai splash screens to various sizes with updated greenStand logo.
You can access them off my dropbox here: https://www.dropbox.com/sh/vyzg08wlb96qvod/AAAYfRG4skgV-xCN6V_EqfXia?dl=0

or download them below

![spalsh_KH_1280_1920](https://user-images.githubusercontent.com/28919873/57912323-56e24480-788a-11e9-9971-62ecf40d71be.png)
![splash_KH_320_200](https://user-images.githubusercontent.com/28919873/57912325-56e24480-788a-11e9-84b8-4cb1bb6e2a92.png)
![splash_KH_480_320](https://user-images.githubusercontent.com/28919873/57912326-56e24480-788a-11e9-8df1-cf44590bfe46.png)
![splash_KH_800_480](https://user-images.githubusercontent.com/28919873/57912327-56e24480-788a-11e9-9068-4b3347982ba1.png)
![spalsh_KH_1280_720](https://user-images.githubusercontent.com/28919873/57912329-577adb00-788a-11e9-84a0-d803404ee942.png)
![splash_KH_1600_960](https://user-images.githubusercontent.com/28919873/57912331-577adb00-788a-11e9-991a-cfb092b0f582.png)
![splash_KH_1920_1280](https://user-images.githubusercontent.com/28919873/57912332-577adb00-788a-11e9-9f63-19f827b10e5c.png)
![spalsh_KH_200_320](https://user-images.githubusercontent.com/28919873/57912333-577adb00-788a-11e9-9774-f37d6c6efd56.PNG)
![spalsh_KH_320_480](https://user-images.githubusercontent.com/28919873/57912334-577adb00-788a-11e9-8984-5b9fc15035f2.png)
![spalsh_KH_480_800](https://user-images.githubusercontent.com/28919873/57912335-58137180-788a-11e9-8764-150ee24b2828.PNG)
![spalsh_KH_720_1280](https://user-images.githubusercontent.com/28919873/57912336-58137180-788a-11e9-87a4-e87f59671664.png)
![spalsh_KH_960_1600](https://user-images.githubusercontent.com/28919873/57912337-58137180-788a-11e9-87ba-acbc14eb5bd8.PNG)

**Comment by deepwinter** [comment]
@Davidezrajay Please store these splash screens in our google drive and then close out this ticket.
