### ISSUE TITLE
crash on sign up

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#307]
See latest fabric issue on Galaxy S8... on sign up page

Fatal Exception: java.lang.IllegalStateExceptionMigration didn't properly handle tree_attributes(org.greenstand.android.TreeTracker.database.entity.TreeAttributesEntity). Expected: TableInfo{name='tree_attributes', columns={_id=Column{name='_id', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=1}, value=Column{name='value', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, tree_id=Column{name='tree_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0}, key=Column{name='key', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}}, foreignKeys=[ForeignKey{referenceTable='tree', onDelete='NO ACTION', onUpdate='CASCADE', columnNames=[tree_id], referenceColumnNames=[_id]}], indices=[]} Found: TableInfo{name='tree_attributes', columns={flavor_id=Column{name='flavor_id', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, app_build=Column{name='app_build', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, app_version=Column{name='app_version', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0}, height_color=Column{name='height_color', type='TEXT', affinity='2', notNull=false, primaryKeyPosition=0}, _id=Column{name='_id', type='INTEGER', affinity='3', notNull=false, primaryKeyPosition=1}}, foreignKeys=[], indices=[]} Raw Text
--
  | org.greenstand.android.TreeTracker.database.AppDatabase_Impl$1.validateMigration (AppDatabase_Impl.java:122)
  | androidx.room.RoomOpenHelper.onUpgrade (RoomOpenHelper.java:89)
  | androidx.room.RoomDatabase.beginTransaction (RoomDatabase.java:275)
  | org.greenstand.android.TreeTracker.database.dao.PlanterDao_Impl.getPlanterDetailsByIdentifier (PlanterDao_Impl.java:448)
  | org.greenstand.android.TreeTracker.managers.PlanterManager.getPlanterByInputtedText (PlanterManager.kt:84)
  | org.greenstand.android.TreeTracker.viewmodels.LoginViewModel.isUserPresentOnDevice (LoginViewModel.kt:70)
  | org.greenstand.android.TreeTracker.fragments.LoginFragment$onViewCreated$7$1.invokeSuspend (LoginFragment.kt:62)
  | kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  | kotlinx.coroutines.DispatchedTask.run (Dispatched.kt:233)
  | kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:594)
  | kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely (CoroutineScheduler.kt:60)
  | kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:742)

**Comment by Elforama** [comment]
This bug means we didn't do the migration correctly. What do you suggest @zaven? This wrong migration was already released on the store.
