### ISSUE TITLE
Count down upload progress from "To sync" to "Uploaded on Data page

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#31]
Need to show progress to the user while we are syncing data to the server.

**Comment by Davidezrajay** [comment]
It used to 'countdown' in the "To Sync" row while syncing

**Comment by Davidezrajay** [comment]
The "Countdown seems to be functioning just fine. It allows them to see that data is being uploaded. 

Users tend to buy small packets of data... 50MB or so. The original thought was that users can pause the data runs out. Then take more photos and resume later. Not sure how this would work with a progress bar.
Close the ticket?

**Comment by Davidezrajay** [comment]
Thank you, it works nicely @Surbhi79 https://github.com/Greenstand/treetracker-android/pull/56
