### ISSUE TITLE
Debug Performance

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#311]
Build the app, add many trees, debug performance issues.  You can add hundreds of debug trees at once by long clicking the 'Add Tree' button.  We want to support at least 2000 trees on the map before setting for performance penalties.

**Comment by joachimHodara** [comment]
Is there any reason we are not using a clustering algorithm/library? 

I might have missed something (still going through the code), but it looks like the map fragment is retrieving a lot of useless data. We are requesting TreeDtos from the database, which also contain planter IDs, photo details and lots of other stuff we don't need to display the markers. We could get away with only retrieving the location (two doubles), and then download the rest lazily if the user clicks on the marker. That approach would be a lot more scalable. 

I have to freshen-up my SQL, but it would be good to only retrieve the data from currently visible zones. I have to check how people usually do that in android, but I am assuming we could use some grid or tree based algorithms to store the data.

Let me know if that sounds reasonable to you and I'll get to work.

**Comment by Elforama** [comment]
We might be able to use this: https://developers.google.com/maps/documentation/android-sdk/utility/marker-clustering

**Comment by deepwinter** [comment]
@joachimHodara Getting started on implementing a grid or tree based lookup (R-trees?) would be a really useful first step - so we can only add what needs to be on the map at a given time.

We also need clustering, for sure.  The main design constraint for clustering is making sure the generation of the clusters itself isn't too slow.  If you have 5000 trees on the map, the clusters need to be calculated, and this has potential to be slow depending on the approach and phone. Clusters can be cached, but when you add a new tree, the clusters must be re-calculated, and this will happen each time a tree is added - so a good caching and regeneration strategy is needed.  We should target support for at least 5000 trees on a given phone, and ideally more.   

Any progress you make on the above engineering problems will be high value!!   A quick solution that takes a first step would be great! A deeper dive to solve the whole problem space even better!

**Comment by joachimHodara** [comment]
I'd better get started then. I'll get back to you when I have a more concrete action plan (exact algo, etc.).

**Comment by joachimHodara** [comment]
I have done some initial testing with the Google Maps Android Marker Clustering Utility. Using the existing code (no optimization whatsoever), I get this behavior on a Nexus 5X with about 5k trees. Overall, it looks pretty good, but not perfect. You can see that the clusterer takes some time to recompute the clusters when I zoom out. Again, zero optimization went into this, we can probably do much better than that, but I guess it's a first step in the right direction...

https://drive.google.com/file/d/1SV-J8PCpc058O4OmV66kEH6uyRWJ9MC8/view?usp=sharing

**Comment by arunbakt** [comment]
Is there a PR for this and any outstanding PR from @joachimHodara that I could take a look into?
