### ISSUE TITLE
Time and Date error in "trees".

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#312]
Using the Android timestamp comes with security vulnerabilities. We should use the GPS date.

**Comment by sebastiangaertner** [comment]
I have just searched for some trees my tracker has uploaded and i could not find them. They are dated 2010 because he seems to be not concerned about his phones date or time setting. This is a real bug in my opinion.

**Comment by sebastiangaertner** [comment]
Actually the date is 1 month off. See image taken on 15th of June

**Comment by Elforama** [comment]
I will start working on this.

**Comment by Elforama** [comment]
After looking into this, it appears the GPS timestamp is set by the system time. Given that, I don't know if there is a way to fix this aside from telling the users to not mess with their phones time settings.

**Comment by sebastiangaertner** [comment]
Well strangely enough I have exactly the same issue on my phone and I belive my rime settings are correct 
--
Sent from myMail for Android Saturday, 15 June 2019, 08:08PM -08:00 from Jonathan Muller  notifications@github.com :

**Comment by Elforama** [comment]
The additional month should be fixed in this PR: https://github.com/Greenstand/treetracker-android/pull/340

Although the date itself cannot be controlled by us.

**Comment by deepwinter** [comment]
@Elforama have you read this thread?  https://stackoverflow.com/questions/7017069/gps-time-in-android

Whenever you receive a fix from the GPS, the method onLocationChanged is called. The parameter to this method is an instance of Location. One of the methods of this parameter is getTime which will give you what you are looking for. That is if I got right what you are looking for. Read more here

shareeditflag
answered Aug 10 '11 at 20:13

Elijah Saounkine
12.5k83146
3
This doesn't actually give you the time from the satellites. It is the device's system time of the fix. – cbrulak Jan 6 '14 at 21:42
2
@cbrulak: Are you sure? The wording is very ambiguous in the docs. E.g. it says "getTime() is useful for ... carefully comparing location fixes across reboot or across devices.". – Timmmm May 22 '14 at 14:07
8
Ok after testing, I can confirm that the time you get from getTime() is the GPS-derived UTC time, and not the device time. (Obviously this only applies if you are using the GPS location provider - for wifi I imagine it is device time.) Note that true "GPS time" is ahead of UTC by 16 seconds. getTime() returns the UTC time derived from GPS, not GPS time itself. – Timmmm May 23 '14 at 9:53

**Comment by deepwinter** [comment]
Getting the GPS time can be rather confusing! To extend discussions in accepted answer, getTime() in onLocationChanged() callback gives different answers depending on how the location (not necessarily GPS) information is retrieved, (based on Nexus 5 testing):

(a) If using Google FusedLocationProviderApi (Google Location Services API) then getProvider() will return 'fused' and getTime() will return devices time (System.currentTimeMillis())

(b) If using Android LocationManager (Android Location API), then, depending on the phone's 'location' settings and requestLocationUpdates settings (LocationManager.NETWORK_PROVIDER and/or LocationManager.GPS_PROVIDER), getProvider() will return:

Either 'network', in which case getTime() will return the devices time (System.currentTimeMillis()).
Or, 'gps', in which case getTime will return the GPS (satellite) time.

**Comment by Elforama** [comment]
Thanks for the info!

So in my testing it always shows GPS date as my device date which goes against what that SO post states. Then I realized I am using a GPS faker app for my location (no signal in my home). I'm guessing the fake GPS app uses my devices time for the GPS time... makes sense. After turning off the fake GPS app I no longer received location updates, which is probably due to no signal in my home. I can't really test outside, but I'm assuming it should work with GPS time.

**Comment by sebastiangaertner** [comment]
How would you explain the 1 months off on the day. On two phones at least. One is a newer Samsung A4 the other a Samsung S7. One located in Tanzania the other in Alaska

**Comment by Elforama** [comment]
I don't know what was causing it. But I cleaned up that part of the code and wasn't able to see anything being off by a month.

**Comment by dezidaisy** [comment]
You could get the android SDK current datetime and convert it to the regional time of your choice before saving.

**Comment by deepwinter** [comment]
@Elforama  #340 resolves this issue, right?

**Comment by deepwinter** [comment]
I have verified this is fixed since #340 by changing my date/time manually.    The date/time reflects what is reported by GPS, which is the correct time.

**Comment by Davidezrajay** [comment]
Just for the records, we are still getting some wild dates here... just got a batch of trees from 2000-04-21 12:19:28. 
App version 1.2.7 (93) Samsung, Model: GT-N7100, Hardware: smdk4x12, Android_release:4.4.2, Sdk: 19, 		2019-12-06 11:56:50
