### ISSUE TITLE
Able to see tree detail screen when clicking inside the Date screen. Overlay issue?

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#314]
While in "Data" screen you can click anywhere and randomly get the "tree detail" info which is supposed to be available only on the "map" screen.

**Comment by Elforama** [comment]
I'll look into a fix for this.

**Comment by sebastiangaertner** [comment]
Is this fixed?

**Comment by arunbakt** [comment]
Hi @sebastiangaertner , I couldn't reproduce it for some reason. When you say 'Data' screen, you are referring to 'Tree Data' screen correct?

**Comment by Elforama** [comment]
@sebastiangaertner Is this still an issue?

**Comment by Elforama** [comment]
No longer relevant with new 2.0 design
