### ISSUE TITLE
Redesign the take picture button

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#327]
User can not see the blue "take a picture" button on screen while outdoors

**Describe the bug**
Users are outdoor and can not see where the take a picture button is once the app is in camera view. (UX should design that!)

**To Reproduce**
go to camera..... 

**Expected behavior**
Way larger (non opacity) simple big massive button which is obvious

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
all phones

**Additional context**

**Comment by deepwinter** [comment]
> 1) Readability is primarily about contrast not color
> Your issue is that the luminosity of your text is too close to your background color. The simplest test you can do is to convert your image to greyscale and compare the intensity of the text to the background. The bigger the difference the better. So a very light yellow or red or blue can all work on a black background if they are light enough (i.e. nearly white).


We need a high contrast button design for our camera button (the one in the actual camera), and to consider color scheme contrast for the overall app.

**Comment by deepwinter** [comment]
aha excellent... @peace's work solves this with the camera button design

![image](https://user-images.githubusercontent.com/364622/59888260-b9dc6500-937b-11e9-8985-a5fb825693fc.png)
![image](https://user-images.githubusercontent.com/364622/59888269-c2cd3680-937b-11e9-808f-240bd0c05f86.png)

**Comment by deepwinter** [comment]
@peacengn Let's create a larger variant of the camera icon for use within the camera - we want it to be unmissable.

**Comment by peacengn** [comment]
![selfieCamera_100x100](https://user-images.githubusercontent.com/20362715/59888985-155c2200-937f-11e9-9273-dc36e738f353.png)

@deepwinter I've made the camera button 100x100, original size 77x77.

**Comment by deepwinter** [comment]
@peacengn great!!!  Can you supply the design assets for the camera button please?  At the 5 resolutions required by Android?

**Comment by Elforama** [comment]
@peacengn @deepwinter Android allows for svg images. Simple icons like that camera are perfect for it. I'd recommend going with an svg as we'd only need 1 size instead of 5. (also makes app size smaller)

**Comment by peacengn** [comment]
[cameraButton.svg.zip](https://github.com/Greenstand/treetracker-android/files/3312604/cameraButton.svg.zip)

cameraButton SVG file

**Comment by deepwinter** [comment]
@sebastiangaertner  Please review this screenshot of the new button.  High contrast black and white.

![image](https://user-images.githubusercontent.com/364622/59891092-a1267c00-9388-11e9-9956-93ed7f6fa7d0.png)

**Comment by Davidezrajay** [comment]
Perfect! Thanks
