### ISSUE TITLE
Sync Function on Map Page

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#328]
**Problem:** 

Many complaints about users not syncing their data and users not being able to find the sync function or know that they need to use it. 

**Solution:** 
There needs to be a button that shows the user when they need to sync. 

**Alternatives**
Auto Sync has been discussed but this is an issue for our target users who buy data bundles for the internet.  

*Please add design mockups in this ticket.

**Comment by Davidezrajay** [comment]
Here are some mockups. Thank you @peacengn ![App Style Guide (1)](https://user-images.githubusercontent.com/25363572/59474415-35299e00-8df3-11e9-9bb6-10abc84067ac.png)
![MAP_HOMEPAGE - with sync button](https://user-images.githubusercontent.com/25363572/59474485-7752df80-8df3-11e9-874c-799ba4bc6de3.png)

**Comment by deepwinter** [comment]
@peacengn We need a way to show progressive progress for users uploading thousands of trees (how many uploaded, or how many to go)

@peace @Davidezrajay we need UI graphics for the cloud upload and cloud spinner graphics.

@peace the badging above shows a single tree, but we need to know how it should look when there are thousands of trees pending.

@peace is the spinner meant to be animated?  Can you design with a progress indicator available in material design?  https://material.io/design/components/progress-indicators.html#usage

**Comment by Davidezrajay** [comment]
Overview: We will move the sync functionality user interaction to the map screen.

1) We will use the ‘Cloud Icon With Arrow’ as placed and sized below as the button that starts the sync process.  This particular specification is not meant to discuss other visual elements on this mockup.

2) The number of trees awaiting sync will be shown using a red circle on this button, using the following layout.  When numbers exceed 999 totals will be listed instead by thousands and tenths of thousands, so 1K, 1.1K, 1.2K…. 2K … etc.

3) When uploading is in process, we will show an extra panel along the top of the map, as shown in the following mockup.  In addition to showing the number of trees to be uploaded and the total number, we will have a standard Android animated progress spinner on the right.  The interior of the progress spinner is a pause icon, which when pressed stops the sync and removes the extra panel from the map view.  The progress spinner reflects the progress of the current sync attempt (so % of the number of trees uploaded since the sync button was pressed, it is not aware tree counts across multiple sync attempts)

4) One missing piece here is that with these changes there is no total count shown of uploaded trees for the device.  It is probably fine to just rely on the map for historical confirmation of trees captured, especially if we can get the map working better under high levels of tree data.

**Comment by deepwinter** [comment]
Closing out this UX version of this issue.
