### ISSUE TITLE
Location/Battery Optimization button

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#33]
If the phone/app is idle, it seems to stops searching for the location. This is good for the battery. Can we add a button to make it search for precise location?

I don't know what this would look like

**Comment by Davidezrajay** [comment]
Intent
The app has a high battery usage. Ideally, the location services would idle (saving battery) while using the app, the user would hold '+' button and app would search location until it reaches appropriate GPS accuracy levels.

**Comment by Davidezrajay** [comment]
Ezra: // Set the interval ceiling to one minute

Can it be set to search on command?
The user holds button and it searches and stops once the photo is taken?

zaven:
not the best idea
the reason being that you will lose your GPS accuracy if you turn it off/on
i am setting it to stop using GPS when the app goes to the background tho
we'd have to experiment with it a bit to see how long it takes to get a good GPS fix
in continuous vs off/on

might not b too bad tho
we don't want to do 'stop once photo'
we don't want to allow photo until they are at a certain accuracy

**Comment by deepwinter** [comment]
Stop location updates when the app goes to background implemented in  72b3ee2e15042e0b7c67392d94ccbb30d615b5e5

**Comment by Davidezrajay** [comment]
![Screenshot_20190327-123953_Device maintenance](https://user-images.githubusercontent.com/25363572/55097295-6a361800-5070-11e9-8deb-c663c0648894.jpg)

Jonathan
We may be able to fix this. Looks like we're requesting location updates every 0 milliseconds (so many updates!). And this is happening on almost every screen in the app.

**Comment by Davidezrajay** [comment]
We will come back to this one...
