### ISSUE TITLE
Justdiggit Flavor “Select tree height class”

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#331]
Replace text on tree hight screen with "Select Tree Height Class"
Translate text to swahili: "Chagua urefu wa mti"

(https://user-images.githubusercontent.com/25363572/59476266-68245f80-8dfc-11e9-9980-b4dbe6ef3a0d.png)

**Comment by deepwinter** [comment]
This issue was closed by PR 343
