### ISSUE TITLE
Switch from crashlytics to firebase

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#338]
Crashlytics is part of firebase now.  We should move off the old crashlytics platform.

**Comment by Elforama** [comment]
Only the crashlytics project owner is able to make this transition. @Davidezrajay Do you know who is the owner of the crashlytics account?

**Comment by Davidezrajay** [comment]
This one looks done?? Super cool! I'll miss fabric!

**Comment by arunbakt** [comment]
@Davidezrajay , Are you saying  this feature done? Shall I close this ticket?
