### ISSUE TITLE
Stuck on splash screen in development

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#350]
**Describe the bug**
Splash screen never goes away when launching dev build on a locked phone.
Observed in JustDiggIt flavor

**To Reproduce**
1. Lock the dev phone
2. Build and install from Android Studio
3. Unlock the phone
4. Stuck on splash screen

**Expected behavior**
Splash screen should clear.  This is probably just related to dev cycle, but is possibility indicative of other use cases that could expose this bug.

**Comment by deepwinter** [comment]
I've observed this now after returning to the app without relaunching it from Android Studio

**Comment by Elforama** [comment]
This is fixed in the DB rewrite.
