### ISSUE TITLE
Add Privacy Policy - Justdiggit flavor

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#366]
Hapa Justdiggit tunaheshimu usiri wako na tutafanya lolote kadri ya uwezo wetu kuendelea kulinda usiri huo. Tutaweka wazi maelezo  ya faragha ya GreenStand kutokana na mazoezi ya kusanya data.

**Jinsi tunavyoshughulikia data:**
Malengo yetu makuu ni kutumia data kwa kutengeneza mazingira bora na kupeana mibadala ya uokoaji uchumi katika maeneo pweke.Tunaamini kuwa Sayansi na miradi yenye kutegemea data yenye tunasanya (yenye si ya kibinafsi) yapaswa kupatikana bure kwa umma.Isipokuwa vinginevyo bila kupewa kibali hatutatoa habari nyeti kama habari kukuhusu kama vile  njia zako za mawasiliano.Ukusanyaji wa data yetu ya msingi unazingatia utafiti wa kisayansi na kuunda mfumo wa uwazi kukusanya data kuhusiana na mchakato wa kuishi wa miti pamoja na taarifa yoyote kuhusiana na mavuno ya utaratibu wa bidhaa zinazohusiana na miti.Maelezo haya ya mpandaji yanajumuisha picha zenye maeneo halisi na ambazo zinazorekodi wakati na data nyingine ya mtumiaji.

Kwa kutumia huduma zetu unakubali kutupa ruhusa kutumia data yako inayohusiana na mazingira na kuifanya ipatikane kwa umma kupitia kwa tovuti yetu. Jina la mtumiaji la kwanza au jina la shirika linaweza onyeshwa pamoja na data za mti unaolingana. Kwa idhini yako kwanza data zingine za mtumizi zinaweza wekwa wazi. Lakini kwa ombi, data zote za mtumizi zinaweza fichwa zisionakane na umma. Nambari za simu /na barua pepe zinaweza tumika na GreenStand kupigia wapanzi, lakini haziwezi pewa watu wengine bila ruhusa. 

**Miradi inayohusiana/ Data za Kisayansi:**
Justdiggit na GreenStand inadhibitisha data za wazi za kisayansi na sera na inakusudia kuzifanya data zozote za kisayansi ambazo zinaweza kuwa na adhari chanya kwa mazingira na maisha ya ustawi wa jamii kupatikana kwa uwazi. Kwa kutumia habari tunazozipata kupitia kwa simu za rununu, tovuti ama mfumo wetu wa data, tunakusudia kutambua shida, suluhisho na mwenendo wa mazingira/afya ya kijamii.Kwa kutumia huduma zetu na software unakubali kutupa ruhusa kuonyesha, kwa umma, miradi inayohusiana na habari za kisayansi. Ikiwa habari zilizokusanywa ni nyeti unaweza wasiliana nasi kwa app@justdiggit.org ao Info@greenstand.org ilituweze kuchukua hatua zinazofaa.  

**Jinsi tunavyo kusanya habari:**
1. Kwa kutumia simu ya rununu:
Picha:zinarekodi wakati, zenye maeneo halisi
Mtumizi hujaza habari yake: jina, barua pepe, jina la shirika, nambari ya simu, maelezo ya shamba 
Mpangilio wa Programu kwa watumiaji
Application analytics: software crash reports, phone make and model.
2.Kwa kutumia tovuti
Tunakusanya data ya mtumiaji:
Hakuna ujumbe ama maelezo kuhusiana na mtuamiaji ama mashirika hayatapeanwa bila idhini yao.Tunatumia data zote zinazohusiana na mtumiaji (jina kamili,namba za simu.barua pepe)salama kwa kutumia kielelezo cha kisasa (cryptography).Majina ya wakulima wa miti na maelezo kuwahusu haitashirikwa kamwe bila idhini yao.

Maelezo kukuhusu:Kwenye programu yetu ya tracker ya miti, tunahitaji jina,barua pepe na kwa hiari nambari ya simu na jina ya shirika. Data yote ya kibinafsi imehifadhiwa kwenye database salama.

Watumiaji wa Programu za simu za rununu: programu zetu za simu ya mikono hukusanya maelezo ya kibinafsi;habari za mtumiaji;jina, anwani ya barua pepe,jina la shirika na nambari ya simu.

**Picha za mtumiaji :**
Programu ya GreenStand ya kufuatilia mti hutumika kwenye mkusanyiko wa picha zilizo rekodi wakati na maeneo halisi.Habari hizi huhifadhiwa katika database salama ambazo huonyeshwa katika mfumo wa treemap. Pia hutumia habari hizi kuzalisha takwimu zinazohusiana na upandaji wa miti.Tunavutiwa tu na picha zinazohusiana na miti,tafadhali usitume picha za aina nyingine. Kwa utumiaji bora wa mfumo huu,picha zote zilizochukuliwa zitahusiana na data za mazingira na Justdiggit na GreenStand haizingatii na kutafsiri picha zinazowekwa kwenye mtandao kama”maelezo ya mtumiaji”.Kwa kutumia programu yetu ya  simu ya rununu unakubali kutupa ruhusa kutumia picha zako.

**Mabadiliko ya sera:**
Ni nia yetu ya kushikilia kanuni za sera  hii,lakini tunaelewa kunawezakana kuwa na  haja ya kubadili  mara kwa mara. Mabadiliko yoyote yatachapishwa kwa tovuti yetu haraka iwezekanavyo.

**Comment by deepwinter** [comment]
Done.
