### ISSUE TITLE
Implement planter data bulk upload via data pipeline

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#390]
Trees are currently uploaded in bulk using json files.  We would like to upload planter info in the same way.   Planter info is currently uploaded one record at a time to our API using the createPlanterRegistration API method.  Instead, planter info should be uploaded just like trees are in SyncDataBundleUseCase.

Planters will be uploaded by placing an array of planter information under the key 'planters' in a JSON file uploaded to S3, using the same target bucket that the tree uploads use.  Planter data could be combined with tree data in a single JSON file, or uploaded in a separate JSON file.

**Comment by Elforama** [comment]
https://github.com/Greenstand/treetracker-android/pull/397
