### ISSUE TITLE
Make upload feedback incremental

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#391]
Even though we are reworking the UI, the current UI for tree uploads should be more informative in the meantime to help with debugging:

Instead of only incrementing by units of 50 as each bulk upload is completed, tree counts for 'Uploaded' and 'To Sync' should be updated every time a image upload completes.

**Comment by sebastiangaertner** [comment]
The minimum requirement here is a dialogue explaining that it might take some minutes before the first 50 are done. 

Ideal solution: To have the actual count as it used to be

Workaround solution: Could we measure the KB that the app is using and displaying that with a small calculation: KB used so far / (Total number of data points to be uploaded * average data point size ) This could be going towards a progress bar going from 0 to 1.
