### ISSUE TITLE
Exposed Amazon Web Services Credentials

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#396]
Exposed Amazon Web Services Credentials

org.greenstand.android.TreeTracker.BuildConfig
org.greenstand.android.TreeTracker.api.ObjectStorageClient
Please fix the issue before: 11/20/2019
Affects APK version 93.

**Comment by deepwinter** [comment]
@Elforama We need to implement Cognito as the credentials provider.  https://github.com/aws-amplify/aws-sdk-android/tree/master/aws-android-sdk-cognito  Get at me when you need something from out AWS account for this.

**Comment by arunbakt** [comment]
The ticket mentions that this issue needs to be fixed before 11/20/2019. Is this already done? Shall we close it?

**Comment by deepwinter** [comment]
I believe this already fixed and this ticket is obsolete.  I integrated cognito some time ago.
