### ISSUE TITLE
Crash on first sync

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#398]
Crash on first sync.

**To Reproduce**
1. Take new phone and install new app
2. Create user and login, track 1 or many trees
3. press sync button 
Result: app crashes.
1. Restart the app 
2. Start sync
Result: Sync is working

All Devices latest app version.

**Comment by Elforama** [comment]
@sebastiangaertner What build was this? (dev/debug/etc..)

**Comment by sebastiangaertner** [comment]
It has not happened again. Should we close this ticket?

**Comment by arunbakt** [comment]
I am closing this given there is no further report on this one. Please re-open if necessary.
