### ISSUE TITLE
Sync stops when receiving phone call

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#399]
The sync process stops when receiving a phone call. This is very discouraging since the chance of receiving a call during upload/sync process being active is very high. Lets say an upload of 1000 trees takes about 45 minutes on a 3G connection. An interruption often results in the user to give up trying to upload.  

**To Reproduce**
1. sync x amount of trees with treetracker on device (A)
2. take another phone and call the active device (A) with treetracker in sync mode
3. check on the sync process (it will have stopped)

**Expected behavior**
The sync to function without interruption once started. 

**Smartphone (please complete the following information):**
 - Device: ALL
 - OS: ALL
 - Version: Latest

**Comment by JonTrimarco** [comment]
Does this delete any of the photos or do they just have to upload again? Do the uploaded images at least make it through?

**Comment by sebastiangaertner** [comment]
Yes they make it through so you just have to get back to the app and restart the sync which is clear to me but for a standard user its gonna be a deal-breaker.

**Comment by sebastiangaertner** [comment]
Actually let me retest this.

**Comment by Elforama** [comment]
@sebastiangaertner Can you please include the name one of the OS, Devices, and versions that this has happened on? It says "ALL" but I am unable to reproduce this.

**Comment by Elforama** [comment]
We can looks into upgrading the WorkManager to the latest: https://developer.android.com/jetpack/androidx/releases/work#2.3.0

**Comment by arunbakt** [comment]
I wasn't able to reproduce it either with my phone which is a Samsung Galaxy S8. Is this still occurring consistently on some specific device?
