### ISSUE TITLE
Planter's image is missing

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#402]
The planter selfi image is not showing up on all the phones.

**Comment by Elforama** [comment]
Can you attach a screenshot or the issue and/or steps to reproduce?

**Comment by Davidezrajay** [comment]
I have not figured out how to duplicate it on my phone. Just there are some users showing up without any planter images.

**Comment by Elforama** [comment]
It would be helpful to know the specs of the phones this is happening on. OS, model, etc...

**Comment by Davidezrajay** [comment]
Thanks.. I'm going to close this one until I figure our more details.

**Comment by Davidezrajay** [comment]
These are first time uses on these devices- App Version 1.2.7, App_build 99, Brand vivo, Manufacture vivo, Model vivo 1713, Hardware mt6755, Android Release 7.0, SDK 24

- App Version 1.2.7, App_build 99, Brand vivo, Manufacture vivo, Model vivo 1816, Hardware mt6716, Android Release 8.1.0, SDK 27
