### ISSUE TITLE
UI Update for Tree Data screen

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#416]
This updated screen will contain new data implemented from endpoint in: https://github.com/Greenstand/treetracker-android/issues/417

The sync/stop button will be replaced with a new button that contains a cloud icon and X icon for the two states.

This screen should function when offline and will require updates to the database to store payment info from the new endpoint.

<img width="688" alt="Screen Shot 2020-02-16 at 6 30 13 PM" src="https://user-images.githubusercontent.com/6439445/74614983-8e687080-50ea-11ea-953c-b1b394474f41.png">

**Comment by arunbakt** [comment]
I have a question regarding the upload button where when a user clicks on it, it starts the sync process and changes the button to show a cross according to the requirement.  

1. Should we give the ability to cancel the upload process via the button with the 'X' icon? Assuming the upload of the local tree data and download of payment data and validated trees happening in two distinct phases,  we could trigger the cancellation safely. Wanted to confirm the user experience.

2. Trying to use a 'X' icon from the material design site, looks weird for my eyes. I suggest we use a solid stop icon instead. Let me know what you think.

**Comment by Davidezrajay** [comment]
A black Square is good. Thanks for your idea.
