### ISSUE TITLE
Android deployment automation

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#42]

**Comment by mckornfield** [comment]
Do you mind providing a bit more context on what this means? Not super familiar with Android but trying to get a sense of what this entails.

**Comment by deepwinter** [comment]
At one point in time, there were services where I could push a tag to a specific branch on github, and the service/server would build the app and send it out to fabric.io for deployment to our testers.  This makes it more straightforward to deploy nightly builds.  It would also be good to be able to do this when sending to the play store.  There may be options that just use gradle and do this locally without a server, or there may be build server options.  First step is to assess what how people are currently addressing this need in devops, last time I set something like this up was a couple years ago.

**Comment by Davidezrajay** [comment]
https://github.com/codepath/android_guides/wiki/Automating-Publishing-to-the-Play-Store

**Comment by Davidezrajay** [comment]
https://github.com/marketplace/category/continuous-integration

**Comment by deepwinter** [comment]
We made progress on this elsewhere.
