### ISSUE TITLE
Treetracker logo within the Android system is outdated. 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#422]
**Describe the bug**
Icon on Android once installed is showing the old logo and Tree Tracker rather than Treetracker

**To Reproduce**
1. Go to play store
2. Click on Greenstand Treetracker
3. install
4. look at your list of apps and see the icon

**Expected behavior**
Correct Icon (ie. Greenstand logo) with Treetracker same as in the Play Store. 
![Treetracker_old_logo](https://user-images.githubusercontent.com/3283800/75348611-3ed93000-58b4-11ea-8856-5a993fdb46dc.jpg)

**Comment by arunbakt** [comment]
@sebastiangaertner  The logo on this ticket looks different than what I find in playstore. Is the icon in this ticket the new logo for Treetracker Android app?

**Comment by Elforama** [comment]
@deepwinter @sebastiangaertner Is this still relevant? Is this saying the the icon of a man/tree is the current icon and the current fully screen icon is wrong?
