### ISSUE TITLE
Design UX for Uploading Data

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#423]
When uploading data, the user does not get any tree by tree upload indication that uploads are happening. Many users are in remote areas with limited service - data upload is a chronic problem.

This is a side effect of our change to bundled tree uploads. Data now uploads in bundles of 50.  

See more Questions related to this issue: https://github.com/Greenstand/treetracker-android/issues/337 

Possible solution: a progress bar. 

![Screenshot_20200229-135926](https://user-images.githubusercontent.com/25363572/75606244-db414380-5afb-11ea-8bf0-c56804170ff4.png)

**Comment by rgesulfo** [comment]
I like your suggestion of progress bar @Davidezrajay. I can mock something up for it :)

**Comment by sebastiangaertner** [comment]
There is a lot of space available so it could even be something like a growing tree but Def. Needs a rough calculation of kb that need to be uploaded and kb uploaded so far

**Comment by sebastiangaertner** [comment]
Related issues #391

**Comment by rgesulfo** [comment]
Hey folks, I'm probably totally off. So please let me know what doesn't work with something like this?
![image](https://user-images.githubusercontent.com/13984657/75645356-4299e900-5c0b-11ea-9dd8-c01cb21d7165.png)
Either we make the progress bar be "small" progress bars representing the actual number of trees to sync or we could even have just one big tree.
![image](https://user-images.githubusercontent.com/13984657/75645557-fc915500-5c0b-11ea-8cac-0b0c6c5250d2.png)
What makes the most sense?
Thanks

**Comment by arunbakt** [comment]
Visually I like the former design to show individual tree upload progress. But given the spec on issue https://github.com/Greenstand/treetracker-android/issues/416, where would this progress screen appear? It can't be in the tree data screen. 

What is the proposed way to navigate to this upload progress screen?

**Comment by EngrTaofeek** [comment]
Fixed
