### ISSUE TITLE
Sign Up Button not showing

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#425]
This issue took place on a Samsung Galaxy J1 Ace which is a small phone and was on Version 1.2.7 from the Play store.

https://youtu.be/rxwD_nvQF2E

The sign up button on the sign up page is not reachable. We were not able to scroll to the bottom of the screen. And we were not able to rotate the screen. 
 
This is the screen and button that were not reachable. 

![Screenshot_20190527-111718_Tree Tracker](https://user-images.githubusercontent.com/25363572/75857741-bd2f5800-5e07-11ea-9e96-f6bdd9bf0ce2.jpg)

**Comment by sebastiangaertner** [comment]
Possible solution is to move the logo(much small and white) into the green bar to the left and use the space taken by the logo for the form.

**Comment by Elforama** [comment]
Now that you mentioned it, I noticed that there would normally be a back arrow in the top left corner. What about making the logo smaller or removing it from the screen entirely? We have our logo on almost every screen in the app already.

**Comment by Davidezrajay** [comment]
Removing the logo sounds like the best.
