### ISSUE TITLE
Add device info to json data bundle upload.

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#434]
Currently the app uploads device information to the devices endpoint in the mobile API.  However this is slow.

Instead we want to put this device info into the JSON data bundle format that we already use for trees and planter registration info, and remove all use of the mobile API from the app (including querying for an access token).

The format is simply to add a 'devices' key to a JSON file that gets uploaded to S3.  It should contain all the same fields and parameters currently sent to the mobile api devices/ endpoint.

Any JSON file send to S3 can therefore have one or more of the following 3 keys

{
   "trees" : [],
   "registrations" : [],
   "devices" : []
}

**Comment by Elforama** [comment]
https://github.com/Greenstand/treetracker-android/pull/435/files
