### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#44]
We need someone to read this code and clean it up. 

It has been through a lot of different developers.

**Comment by habbs19** [comment]
I can do this. Where to find the code?

**Comment by deepwinter** [comment]
https://github.com/Greenstand/treetracker-android

**Comment by deepwinter** [comment]
master branch is fine.

**Comment by Davidezrajay** [comment]
https://github.com/Greenstand/treetracker-android/issues/44
