### ISSUE TITLE
Send to wallet 'x' feature for Tree Tracker Money app 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#446]
### **Note: This spec needs a deep analysis prior to implementation.**

**Goal:** 
Verify that individuals on the ground actually transferred their data and were paid for it and where not just scammed by the individual tracking. 

Users need a way to transfer their data / send it to other users or other organizations. 

Many organizations claim 'ownership' over the same set of trees. There needs to be a way for users to send their trees to either a village coordinator or a managing organization.

**Challenges include:**
1. Verifying payments were made (cash or mobile money)
2. Verifying that the actual transfer of tree data from the planter to the village coordinator.  
3. This transfer takes place the ground level, offline and before the data has been uploaded verified or tokenized.

**Suggested solution:** 
Add a transfer to field and button allowing the user to enter a wallet handle name. This can be on the data upload page, individual tree 'save page' or set as default at the time of "login"

This should be at a per tree capture level in the `trees` table. 

Ideally this would have a 'payment amount' field and force a selfie or other planter verification at the time of transfer.  

Note: the closest we can come to verifying a cash transfers to a user is to receive a photo of the user with the cash. 

This is different than the Troken app, in that this data is not yet verified, tokenized and placed in a wallet. Although, completion of this ticket should trigger the transfer at the time of tokenization.

**Comment by Elforama** [comment]
@deepwinter @Davidezrajay @arunbakt We should have a meeting to discuss this in more detail and come up with a full spec for it.

**Comment by Elforama** [comment]
This has been speced out and will be the Token Xfer screen.
