### ISSUE TITLE
In app language switching

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#447]
Allow a user to change languages without leaving the app.

Many users don't speak english, yet they can't change their phones language setting. Additionally, some phones don't support the languages that are required. We want to find a way to have users switch languages while still in the app. Perhaps as simple as a button that's easy to access.

**Comment by Elforama** [comment]
This code snippet will change the app to the given locale:
```
val locale = Locale("sw")
        val config = Configuration(context!!.resources.configuration)
        Locale.setDefault(locale)
        config.setLocale(locale)

        resources.updateConfiguration(
            config,
            resources.displayMetrics
        )
```

**Comment by Davidezrajay** [comment]
Please design this in the signup flow and on the settings page. It should be designed in a way that if the buttons are hidden in specific versions of the app, it will not negatively affect the user.
