### ISSUE TITLE
Put camera permission check before navigating to new tree fragment

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#456]
If we get to the new tree fragment without already accepting the permission, the screen shows up for a few seconds before showing the dialog. We don't want them to get to this screen unless we know they can take a picture.

**Comment by arunbakt** [comment]
Hi @Elforama,
 The prompt asking for camera permission is almost immediate after the new tree fragment is rendered. This is one time pop up and is relevant to the activity the user is going to take, unlike the option where the pop up would be shown right after the app first loads.  I like the idea of waiting until the need arises asking for permission. Is that a not a good android practice? You must have had some reason for it, want to know before I make the change.

**Comment by Elforama** [comment]
The reason is because if they deny it, they are kicked off that screen. This is a weird user experience.

**Comment by Elforama** [comment]
No longer relevant with new 2.0 design
