### ISSUE TITLE
Convergence parameter  for GPS data when adding a tree

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/treetracker-android#463]
GPS location convergence parameter is the variation from the average that meets an allowed maximum threshold value below which a tree capture with device's camera is enabled.  When the planter intends to add a tree, tapping add a tree button should result in a spinner graphic while waiting for the convergence parameter. 

The convergence parameter is the greater of the latitude/longitude standard deviations of a set of recent GPS co-ordinates (ones captured from the time 'Add Tree' is clicked).  The set is last 'n' location ('n' is configurable) values  used in computing the convergence parameter (as standard deviation). When the convergence value computed with n set meets the max threshold, we let the Camera screen clickable to capture the tree. If not, we wait for the next n+1-n sequential  location value and compute the convergence parameter again. If this parameter is within the maximum allowed convergence threshold (configured as a property value), the planter is allowed to take the picture. If not, after a configurable timeout , the planter is allowed to take the picture anyways.

This issue is a subtask created from the requirements specified [here](https://github.com/Greenstand/Development-Overview/wiki/Android-v1.4-GPS-location-data-collection).

**Comment by deepwinter** [comment]
accept capture when 

MAX(STDDEV(latitudes), STDDEV(longitudes)) < CONVERGENCE PARAMETER
where latitudes and longitudes are the last N latitudes and longitudes received from GPS respectively

**Comment by arunbakt** [comment]
@deepwinter what if we have separate convergence threshold for latitude and longitude. Would that make the data closer to the true location of the tree.
i.e
  MAX(stddev(latitudes)) < latitude_convergence_parameter and
  MAX(stddev(longitude)) < longitude_convergence_parameter

**Comment by arunbakt** [comment]
Issue addressed in the following PR and merged.
https://github.com/Greenstand/treetracker-android/pull/478
