### ISSUE TITLE
Creating an improved Homepage design

### ISSUE THREAD

**Issue by shubhamk008** [Greenstand/treetracker-android#470]
We need to get rid of loading the map on the homepage. The UX team must create multiple mock-ups, iterate on the design with essential elements and then share the final screen to the developers. Multiple attempts on this have been made in the past, so feel free to take inspiration from them.

**Image 1**
![image](https://user-images.githubusercontent.com/12235388/90959713-5b989e00-e4ba-11ea-8d55-ffc898a266df.png)
--------------------------------------------------------------------------------------------------

**Image 2**
![image](https://user-images.githubusercontent.com/12235388/90959866-36f0f600-e4bb-11ea-9dd5-1ccefa17e6c3.png)
--------------------------------------------------------------------------------------------------

**Image 3**
![image](https://user-images.githubusercontent.com/12235388/90959889-4b34f300-e4bb-11ea-8729-5068a36a44cc.png)
--------------------------------------------------------------------------------------------------

**Image 4**
![image](https://user-images.githubusercontent.com/12235388/90959924-8cc59e00-e4bb-11ea-8665-f23a0d6dad72.png)
--------------------------------------------------------------------------------------------------

**Image 5**
![image](https://user-images.githubusercontent.com/12235388/90959895-54be5b00-e4bb-11ea-9a9c-4637dedb5267.png)
--------------------------------------------------------------------------------------------------

**Image 6**
![image](https://user-images.githubusercontent.com/12235388/90959900-58ea7880-e4bb-11ea-8c29-9c519cc7a852.png)

**Comment by Elforama** [comment]
No longer relevant with new 2.0 design
