### ISSUE TITLE
Taking multiple photos in "Add Tree" flow

### ISSUE THREAD

**Issue by shubhamk008** [Greenstand/treetracker-android#471]
Users find it difficult to take multiple photos per tree in the same "Add Tree" flow.
The UX team must design an option for users who would like to capture more than one snap.

**Comment by arunbakt** [comment]
You may also want to take a look at the issue number 462 ( location data and [related product doc](https://github.com/Greenstand/treetracker-android/wiki/Device-Data-Capture) ) to see how this impacts that requirement.

**Comment by EngrTaofeek** [comment]
Fixed
