### ISSUE TITLE
Signup and login button covered by keyboard

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#472]
**Describe the bug**
Keyboard covering the signup and login button see left side. Proposed design on right side
![Treetracker_login](https://user-images.githubusercontent.com/3283800/91028858-bb03c480-e606-11ea-8389-32515f0ef373.png)

**To Reproduce**
1. install app
2. open
3. on login screen the keyboard covers the login and signup button

**Comment by Elforama** [comment]
No longer relevant with new 2.0 design
