### ISSUE TITLE
Colors in app need to be adjusted to the brand guidelines. Treetracker spelling as one word.

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#473]
All Colours need to be adjusted to the brand guidelines. Including the logo. See screenshot. 
See right side for proposed design. Logo can be black as well. 

![Treetracker_login](https://user-images.githubusercontent.com/3283800/91029158-159d2080-e607-11ea-9899-53447dedcfbd.png)

**Comment by shubhamk008** [comment]
![](https://files.slack.com/files-pri/T6WR1QS8J-F018Z790479/login.png)

Consider removing "Forgot password" for the final mockup.

**Comment by nmcharlton** [comment]
Can we also split the word 'login' on the button to be 'log in' (the verb form)?

**Comment by shubhamk008** [comment]
Note for reader: Retain available space in the bottom half for the keyboard.
@sebastiangaertner we can close the Issue #472 since it's being considered here.
