### ISSUE TITLE
Load deleted images from network

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#483]
After uploading a tree image we delete it locally to save space. This is fine for most parts of the app except when clicking on a tree in the map. This will load a tree details screen that shows an image of the tree. 

Currently it will not show the tree if it's been uploaded (since it was deleted).

We need to support network images. The solution needs to also support offline images that are downloaded from a network.

**Glide** is a library that we should look into since it supports both these use cases with very little work on our part.

**Comment by EngrTaofeek** [comment]
I think this issue has to do with the old app as web map currently uses web view in the app.
