### ISSUE TITLE
Kasiki Hai - GPS point as tree base

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#490]
For the Kasiki Hai white label we want to add another GPS capture point triggered by a button that will be pressed at the base of the tree. This is to give a more accurate measurement of the tree location.

Open Questions: 
- @deepwinter Is this feature needed now that we are upgrading our GPS system?

**Comment by deepwinter** [comment]
yes, still needed.  this is because the plants they track are bigger and typically photographed from a few meters away.  so that picture does not give a good position.

**Comment by Elforama** [comment]
@deepwinter In that case, do we want to hold off on convergence for this app flavor until they press the new GPS button in the tree capture screen? This would be instead of waiting for convergence for the photo.

**Comment by deepwinter** [comment]
totally, yes.   good catch, didn't occur to me but absolutely convergence needs to happen at the tree base.

**Comment by arunbakt** [comment]
A button at the base of the tree meaning, the pictures are usually taken at a distance from the tree and users of this version are required to take a picture at the base of the tree? Are we talking about a new flow that prompts the user to walk to the base of the tree?

**Comment by Elforama** [comment]
I think I'll just add a button to the NewTreeFragment that starts the convergence instead of the camera.
