### ISSUE TITLE
Device ID seems to not be added to the database

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#506]
Checking user 1987 for example there is no device_id attached to that planters tree entries. See screenshot . Tying to figure out why that phone produces such large images. 
![Screenshot 2020-10-02 at 19 23 17](https://user-images.githubusercontent.com/3283800/94946694-30f02b00-04e5-11eb-9ed1-2f84a2f2b6c7.png)

**Comment by Elforama** [comment]
Device ID is being added on client side. This is either a server issue, or a unique device issue.

**Comment by sebastiangaertner** [comment]
Is it possibly since we renamed user to planter?
