### ISSUE TITLE
Big images uploaded

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#507]
I could not see what device it is since there is the issue #506 but this particular Device also makes very large images see screenshot. 
![Screenshot 2020-10-02 at 19 19 00](https://user-images.githubusercontent.com/3283800/94946855-685ed780-04e5-11eb-9bf7-727ca5347753.png)

**Comment by Elforama** [comment]
Since there is no more info to go off of, I will close this issue. The current dev version of the app is scaling all images down.

**Comment by Elforama** [comment]
Since there is no more info to go off of, I will close this issue. The current dev version of the app is scaling all images down.

**Comment by arunbakt** [comment]
Addressed in the following issue https://github.com/Greenstand/treetracker-android/issues/522
