### ISSUE TITLE
Crash On Sync

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#51]
Device: Galaxy J1
 
public synchronized SQLiteDatabase openDatabase() {
        mOpenCounter++;
        if(mOpenCounter == 1) {
            // Opening new database
            mDatabase = mDbHelper.getWritableDatabase();
        }
        return mDatabase;
    }
    public synchronized void closeDatabase() {
        mOpenCounter--;
        if(mOpenCounter == 0) {
            // Closing database
            mDatabase.close();

**Comment by Davidezrajay** [comment]
[org.greenstand.android.treetracker_issue_3_crash_5A99C46800BE00016B9F0A2DC1325116_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1776822/org.greenstand.android.treetracker_issue_3_crash_5A99C46800BE00016B9F0A2DC1325116_DNE_0_v2.txt)

**Comment by deepwinter** [comment]
The database should never be closed once it's opened IMO.

**Comment by deepwinter** [comment]
Closing this out and creating a new ticket for database never close.
