### ISSUE TITLE
Country code selection on login screen

### ISSUE THREAD

**Issue by shubhamk008** [Greenstand/treetracker-android#512]
In the new login screen, users will require to provide their country code while logging in using their phone numbers. This will be done to ensure that phone numbers are unique across geographies.

How do we intend to get the country code? Is it using GPS, some device setting or manual selection?
Once the solution is finalized from the technical side considering its feasibility, we can hand it over to the design team.

**Comment by sebastiangaertner** [comment]
Does the Device information not carry a country code?

**Comment by Elforama** [comment]
We can get the country code from a users sim, assuming it's their phone/sim. However, if it's not, then we are possibly adding an incorrect country code. If they plant for their # again on another phone, perhaps their own, it could add a different country code. This would result in 2 accounts for 1 user without them knowing.

**Comment by sebastiangaertner** [comment]
Its a bit tricky indeed. Could there be a solution here https://github.com/google/libphonenumber or here https://github.com/hbb20/CountryCodePickerProject 
There seems to be a nice article https://www.xspdf.com/resolution/52327635.html

**Comment by deepwinter** [comment]
we have the GPS location of the user when they register, this can be cross referenced against our countries shapes.

**Comment by shubhamk008** [comment]
Note for reader: After this issue is resolved, move to issue #473 .

**Comment by Elforama** [comment]
No longer relevant with new 2.0 design. User will input any phone number they want.
