### ISSUE TITLE
Setup justdiggit configuration in firebase 

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/treetracker-android#518]
Setup justdiggit project in firebase and commit the configuration file to the repository

**Comment by Elforama** [comment]
@arunbakt  I didn't see this issue until now. I have setup a basic justdiggit version in firebase called "kasiki hai". But I have not done anything yet with the json config.

**Comment by arunbakt** [comment]
https://github.com/Greenstand/treetracker-android/pull/519
