### ISSUE TITLE
Keyboard needs to fold in after adding DBH and clicking "Weka alama ya GPS"

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#521]
See screenshot the button "Weka alama ya GPS" appears to be the button to press after  adding the DBH but below is the actual "IJAYO" button is covered by the keyboard. Can the keyboard disappear(fold in) when clicking on the "Weka Alama ya GPS" button?
![Screenshot_20201023_092327_org greenstand android TreeTracker justdiggit debug](https://user-images.githubusercontent.com/3283800/96964160-a6fb1700-1512-11eb-87ab-8fd809eb140c.jpg)

**Comment by arunbakt** [comment]
Hi @sebastiangaertner ,

You could press the blue `Return` button to dismiss the window. We could programmatically dismiss it as well, but the code for this would read out of context at the place it appears.  Just wanted to let you know this other option exists. 

Let me know you rather wants automatically folded as you have requested. Will go and make the change.

**Comment by arunbakt** [comment]
Fixed and merged to master
