### ISSUE TITLE
Finalize format for location track data uploads

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#534]
Location track data uploads currently show escape characters and follow a different format than the other JSON files

Example:
`["{\"accuracy\":6.432,\"capturedAt\":1601756569360,\"convergenceStatus\":null,\"latitude\":47.06804996,\"longitude\":-122.93840958,\"planterCheckInId\":1,\"treeUuid\":null}","{\"accuracy\":4.288,\"capturedAt\":1601756569497,\"convergenceStatus\":null,\"latitude\":47.0680119,\"longitude\":-122.93839926,\"planterCheckInId\":1,\"treeUuid\":null}","{\"accuracy\":4.288,\"capturedAt\":1601756570413,\"convergenceStatus\":null,\"latitude\":47.06799941,\"longitude\":-122.93839476,\"planterCheckInId\":1,\"treeUuid\":null}","{\"accuracy\":4.288,\"capturedAt\":1601756571437,\"convergenceStatus\":\"NOT_CONVERGED\",\"latitude\":47.06798105,\"longitude\":-122.93838234,\"planterCheckInId\":1,\"treeUuid\":\"04197eda-5fee-4998-aa92-a19a3e63a602\"}","`

The desired format format for the file would not have escape characters and follow the following format:

`{"locations":[{"accuracy":6.432,"capturedAt":1601756569360,"convergenceStatus":null,"latitude":47.06804996,"longitude":-122.93840958,"planterCheckInId":1,"treeUuid":null}]`

**Comment by arunbakt** [comment]
Fixed and merged to master.
https://github.com/Greenstand/treetracker-android/pull/537

**Comment by arunbakt** [comment]
While the escape character is addressed, the desired format to have the array under a field named "locations" is not changed. Reopening this ticket to address that part.

**Comment by arunbakt** [comment]
Fixed and merged to master.
https://github.com/Greenstand/treetracker-android/pull/542
