### ISSUE TITLE
Use mean converged location for default capture location

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#535]
Before saving a new capture, use the mean of all recorded converged location measurements as the default location attached to that capture record.

**Comment by arunbakt** [comment]
@deepwinter what do we do when GPS wanders after a convergence was within allowed limit, but the user hasn't captured the image yet. But finishes capture when the GPS is currently wandering. In this case I feel it is reasonable to go with the last calculated mean of lat/long of converged data. Let me know what you think.

**Comment by arunbakt** [comment]
Change made and merged to master. https://github.com/Greenstand/treetracker-android/pull/545
