### ISSUE TITLE
Profile and tree pic rotated

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#539]
Profile and tree pic rotated.

I believe this one has been fixed by a recent PR, but perhaps was not released to QC yet?

Reporter: Sander.

**Comment by arunbakt** [comment]
Yes, I didn't merge the master back to release 1.4 yet. Will do it once I have a two or more fixes ready from milestone 11.

**Comment by arunbakt** [comment]
There is an issue with the profile picture (its rotation is in the opposite direction of that of the tree images). I have raised a PR for this. But tree images are not rotated as reported.

**Comment by arunbakt** [comment]
Resolved and merged to master. Waiting to be merged into the release 1.4 branch
