### ISSUE TITLE
Crash On Sync Techno Phone

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#54]
Same as the last issue? He managed to upload 27 out of 300 photos before it started crashing. 

 [org.greenstand.android.treetracker_issue_3_crash_5A9ACE2200550001193F147EAB2FC746_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1778061/org.greenstand.android.treetracker_issue_3_crash_5A9ACE2200550001193F147EAB2FC746_DNE_0_v2.txt)

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

Caused by com.google.gson.JsonSyntaxException
java.lang.NumberFormatException: For input string: "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2018-03-03 08:11:20-5' for key 'time_created' (SQL: insert into `notes` (`content`, `time_created`, `user_id`) values (, 2018-03-03 08:11:20, 5)) #0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\Database\Connection->run('insert into `no...', Array, Object(Closure)) #1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(295): Illuminate\Database\Connection->statement('insert into `no...', Array) #2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `no...', Array) #3 /var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1764): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `no...', Array, 'id') #4 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #5 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(919): call_user_func_array(Array, Array) #6 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1512): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #7 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1512): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #8 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #9 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1390): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #10 /var/www/app/controllers/TreeController.php(126): Illuminate\Database\Eloquent\Model->save() #11 [internal function]: TreeController->create() #12 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array) #13 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('create', Array) #14 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(TreeController), Object(Illuminate\Routing\Route), 'create') #15 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'TreeController', 'create') #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(104): call_user_func_array(Object(Closure), Array) #18 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #20 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 /var/www/vendor/laravel/framework/src/Illuminate/Http/FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true) #23 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true) #24 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true) #25 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true) #26 /var/www/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true) #27 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request)) #28 /var/www/public/index.php(49): Illuminate\Foundation\Application->run() #29 {main}"
com.google.gson.internal.bind.TypeAdapters$7.read

Caused by java.lang.NumberFormatException
For input string: "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2018-03-03 08:11:20-5' for key 'time_created' (SQL: insert into `notes` (`content`, `time_created`, `user_id`) values (, 2018-03-03 08:11:20, 5)) #0 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(338): Illuminate\Database\Connection->run('insert into `no...', Array, Object(Closure)) #1 /var/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(295): Illuminate\Database\Connection->statement('insert into `no...', Array) #2 /var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `no...', Array) #3 /var/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1764): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `no...', Array, 'id') #4 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id') #5 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(919): call_user_func_array(Array, Array) #6 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1512): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array) #7 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1512): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id') #8 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1482): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array) #9 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1390): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder)) #10 /var/www/app/controllers/TreeController.php(126): Illuminate\Database\Eloquent\Model->save() #11 [internal function]: TreeController->create() #12 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array) #13 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('create', Array) #14 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(TreeController), Object(Illuminate\Routing\Route), 'create') #15 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(934): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'TreeController', 'create') #16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #17 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(104): call_user_func_array(Object(Closure), Array) #18 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1000): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(968): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #20 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(738): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #21 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #22 /var/www/vendor/laravel/framework/src/Illuminate/Http/FrameGuard.php(38): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true) #23 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true) #24 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true) #25 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true) #26 /var/www/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true) #27 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(606): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request)) #28 /var/www/public/index.php(49): Illuminate\Foundation\Application->run() #29 {main}"

**Comment by deepwinter** [comment]
We are getting an error message from the server and not reading it correctly on the phone, causing an a crash.

**Comment by deepwinter** [comment]
There is a pre-existing error in the database structure that is triggering the server side problem.  time_created appears to have been set up as a unique key, when of course there could be be multiple notes that share the same creation time.

**Comment by deepwinter** [comment]
All these notes are also empty, and probably shouldn't have had records created anyway.

**Comment by deepwinter** [comment]
I've dropped the unique key index on time_created for now, which should avoid this server error and the resulting crash in Android.  We need to analyze why 2 notes were attempted to be inserted with the same time, and also create code in Android to not crash but rather skip over a tree that does not sync.

**Comment by Surbhi79** [comment]
@deepwinter Is the application still taking two notes ??

**Comment by deepwinter** [comment]
@Surbhi79 Oh was that an issue before?  Making 2 notes per tree?

**Comment by Surbhi79** [comment]
No, it wasn't. That's why it's confusing.

**Comment by deepwinter** [comment]
want to take a look at that hypothesis?

**Comment by Surbhi79** [comment]
Sure. But how?

**Comment by Surbhi79** [comment]
Do you have a link through which I can view database?

**Comment by deepwinter** [comment]
Oh I see what you mean.  yeah I don't know either.  you'll have to debug it and see how 2 notes got the same created time.

**Comment by Surbhi79** [comment]
Or maybe a screenshot of the database that caused this issue

**Comment by deepwinter** [comment]
it's just an empty note text field, user id, and a date.  The note shouldn't even really be getting saved anyway, because it's empty.  But besides that, the userid and data were both identical to pre-existing record, which was thrown as an error by a unique key index that was set up.

**Comment by Surbhi79** [comment]
So were all the other rows, that are below the error causing row having time created field recorded twice??

**Comment by deepwinter** [comment]
well nothing got recorded twice, because it threw that error

**Comment by deepwinter** [comment]
it's probably actually just that a tree for some reason was being uploaded twice

**Comment by deepwinter** [comment]
Will be addressed in #118
