### ISSUE TITLE
"No trees to send" error

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#541]
On uploading it gave me this “No trees to send” error while only 1 of 2 trees had been uploaded. When I checked later all trees were uploaded, so it could be that the numbers had not been updated on my screen.

Reporter: Sander

**Comment by Elforama** [comment]
I can't find the text "No trees to send" in the codebase.

**Comment by arunbakt** [comment]
May be he meant "Nothing to sync"?

**Comment by Elforama** [comment]
App being redesigned, no longer relevant.
