### ISSUE TITLE
Some planter ids are duplicated on ingestion

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#554]
Some registration payload do not reach the cloud.  This cascades into a poorly handled edge case in the data pipeline code that causes a new planter record to be created for each tree uploaded.  This has only affected a very limited number of uploads so far and appears to be pretty rare.

The issue is also happening reliably on the test environment.  Next step is to understand the usage conditions that create the problem - code tracing did not reveal any obvious oversights.

**Comment by arunbakt** [comment]
I investigated this issue for planter identifier 099526317 and 0772946  whose registration were missing the database.

I downloaded the files uploaded on 11.10.2020 from s3 and investigated files that had  relatively smaller size(3digit sizes) assuming the registrations will have smaller sized files. I only see the phone identifier in the tree capture file and no registration data turned up for the identifier 099526317  in the set I downloaded. 


But for the user with identifier 0772946 I found the registration record in the upload file. I suspect this is probably a upstream processing issue during ingestion and not in the device. Closing the issue, please re-open if you find new info and suspect this is still the device.

Here is the file name and its related record.
`2020.11.10.14.36.13_ca90c48e-7da9-4694-9aad-640fdf13b1aa_87aed0ec1f3071a92f8ff088041660de:{"devices":[{"androidRelease":"5.0","app_version":"1.3.0","brand":"samsung","device":"hlte","device_identifier":"868cb787efd91c46","hardware":"qcom","instanceId":"
erlzT4oQ-kg","manufacturer":"samsung","model":"SM-N9005","serial":"91ef9603","androidSdkVersion":21,"app_build":120}],"registrations":[{"device_identifier":"868cb787efd91c46","first_name":"Conteh","last_name":"Rosaline","lat":8.47560622,"lon":-13.218977
1,"organization":"FCCAFW ","planter_identifier":"0772946"}]}`

**Comment by sebastiangaertner** [comment]
Thank you. I will keep an eye on it. 
There was some more identifiers though: 08855006 074897309 088464930 07684570

**Comment by arunbakt** [comment]
Reopening the issue since this could be because of bug during ingestion (off the device) and upload registrations (on the device).
Some of the identifiers 07684570, 0772946 do exist in the uploaded registration files but others are not present.

**Comment by sebastiangaertner** [comment]
Its still happening. We have a case now with userid 3021
3020
3019
3018
3017
3016
3015
3014
3013
3012
3011
3010
3009
3008
3007
3006
3005
3004
3003
3002
3001
3000
2999
2998
2997
2996
2995
2994 being the same

**Comment by deepwinter** [comment]
This has been resolved and deployed in 4.1.1
