### ISSUE TITLE
Managed to create two ids sharing the same image with identical timestamps 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#558]
**Describe the bug**
When vigorously testing the upload by turning internet on and off during the  upload, creating multiple logins on the phone and tracking a couple trees each i managed to create the rare case of two uids with the same image. Tree id
418300 and 418299 see screenshot two on the laft

**To Reproduce**
1. start and stop the upload, interrupt the internet connection during upload several times. 

**Expected behavior**
Should never use one image twice. 

 - Version 1.4.1 live version from Playstore Greenstand Treetracker
 - Device: Huawei P30
 
![Screenshot 2020-11-19 at 12 29 23](https://user-images.githubusercontent.com/3283800/99762608-fb8db400-2b09-11eb-8db1-90a0af45b1fc.png)

**Comment by deepwinter** [comment]
Please check the UUIDs on these.  Are they different?  And please post the 2 UUIDs.
The UUID is generated on the phone, and the API will only create a capture record for a UUID one time.  So It's likely something that happened early in the capture workflow on the phone, but we need to see those UUIDs to make sure.

**Comment by arunbakt** [comment]
The records for the tree id has the following uuids and they are different.  Looks like these captures are caught in quick succession and have two separate image urls.  

Could it be that the you managed to take the  picture of the tree in quick succession? 

418299	b48b82df-8f60-4ce0-a36d-94fd89181df2	https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2020.11.19.12.02.24_-3.3609136171852825_36.83733946174589_767f7962-924e-4e32-a1a8-09def4300a28_IMG_20201119_115946_7333749870633022062.jpg	2020-11-19 08:59:48

418300	707311c0-c64d-4751-919a-48e847a2cc3c	https://treetracker-production-images.s3.eu-central-1.amazonaws.com/2020.11.19.12.02.37_-3.360911549745257_36.83734154244342_60d48991-cbbe-491b-8bb3-b7a30e90b66f_IMG_20201119_115956_3151198485063967244.jpg	2020-11-19 08:59:56

**Comment by arunbakt** [comment]
I also notice these two images though look same, closely observing, they are two distinct images.

**Comment by deepwinter** [comment]
That makes more sense and fits with the assumptions of how our platform works.  It remain peculiar and notable that the timestamp is the same between the captures.  What is the current source of the timestamp in the capture?  It also seems impossible for a capture to happen within the same second, and also more so impossible because the assessing location functional takes much longer than a second.

**Comment by arunbakt** [comment]
The two pictures are taken 8 seconds apart. Though very short duration between capturing trees, I think it is possible for it to happen.

**Comment by deepwinter** [comment]
@sebastiangaertner your original report states that timestamps are 'identical' and that images are also 'identical'.  However, on further research the timestamps are 8 seconds apart, and the images are in fact different (though only slightly).  This is consistent with two captures that happened 8 seconds apart, and is within the normal use of the app.   I am closing this ticket as an invalid bug report as there is no evidence of duplicated data.   If you have other examples of duplicated data that fit the original report, please append re-open the ticket!  Thank you!
