### ISSUE TITLE
Planter Image seems to not be captured anymore

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#567]
Running the query 

select devices.android_id, devices.app_version, devices.app_build,devices.manufacturer,devices.brand, devices.model, devices.android_release, planter_registrations.first_name,planter_registrations.last_name FROM
devices JOIN planter_registrations ON
devices.android_id = planter_registrations.device_identifier AND planter_registrations.planter_id IN(2864,3158)

will give you two planters info 2864 has the planter image using App version 1.3.0 build 120 and planter
3158 has App version 1.4.1 build 126

Planter 2864 has the image attached and 3158 is missing the image which points towards version 1.4.1 having an issue with the planterimage in the trees table.

**Comment by arunbakt** [comment]
I don't think the null planter_image_url values is isolated to 1.4.1, it is found in app versions 1.3.0

`select` planter_id, devices.android_id, devices.app_version, devices.app_build, devices.manufacturer,
 planter_registrations.first_name,planter_registrations.last_name FROM
devices JOIN planter_registrations ON
devices.android_id = planter_registrations.device_identifier AND planter_registrations.planter_id in (select planter_id
 from trees where time_created > date(now())-5  and planter_photo_url ='')
`

There was a bug in the planter check in upload process all the way until app version 1.4.2. A s3 client exception would leave the planter image url to be left as null and not reprocessed at all. This in addition to another bug where an incorrect foreign key was used to retrieve records while processing the upload. Both got fixed.  The fix put in handles the exception correctly and we retry the failed uploads on second attempt. 

Until the devices out there update their version to 1.4.2 version, we might see these null urls for planter_image_urls in trees table.  

The above is my analysis to the best of my understanding. Will update if I find anything new.

**Comment by arunbakt** [comment]
In addition, the tree uploads currently is independent of whether planter checkin photo url is successfully uploaded or not.
Thus, if something were to go bad during s3 upload in upstream photo url upload, the tree uploads continues.  But the tree request relies on planter checkin's photo url which may be null at the time (it will be populated later correctly on another sync).

What do we do in that case? Should we defer the tree upload until the photo url  is updated?

**Comment by arunbakt** [comment]
@sebastiangaertner,  it would useful to understand how critical it is to have the planter image url in the trees table. Specifically, should we defer tree capture uploads for planter checkins that don't have the image url uploaded successfully yet?

**Comment by sebastiangaertner** [comment]
It a good question. I never quite understood why it is in the "trees" table since we could save a lot of DB space to not have the planter_image living in there. Is planter_registrations not the correct place for this?

**Comment by arunbakt** [comment]
Yes, each planter checkin  results in a image upload. Spoke with Zaven about the issue and we came to a conclusion for the problem by uploading a reference to the check-in instead of using the image url directly on the device. That way the upload process for each data can stay independent of each other. The pipeline process could retrieve the image url when available and update the records accordingly. I need to look into the details on it.
