### ISSUE TITLE
Field Transfer Milestone 1

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#570]
UI:
Add a field called 'field transfer wallet' to the 'save capture' UI.  Make the value entered into this wallet 'sticky' per checked in user session (definition of a session can be loose for now, will be defined by next UI updates).  This value will be attached to each capture when stored locally on the phone.

Backend:
When uploading data packs, include a new key in the JSON called 'transfers'.  The value for this key should be an array of pending transfers in the following format:

```
{
   transfers: [
       {
            uuid:  $treeUUID,
            receiverWallet: $fieldTransferWallet
       }
   ]
}
```

This key can be included in any data pack and does not need to be in an isolated file.

**Comment by Elforama** [comment]
feature is in branch "wallet_testing"
