### ISSUE TITLE
ERROR: treetracker.keys.properties

### ISSUE THREAD

**Issue by jiayounokim** [Greenstand/treetracker-android#604]
**Describe the bug**

```
A problem occurred evaluating project ':app'.
> treetracker.keys.properties (The system cannot find the file specified)
```

**To Reproduce**

1. Clone and Compiles the App.

**Expected behavior**

To have treetracker.keys.properties file available.

**Additional context**

Where is this file and how to solve this bug?

**Comment by Elforama** [comment]
Please refer to https://github.com/Greenstand/treetracker-android/wiki/Environment-Setup
