### ISSUE TITLE
Update Image Confirmation Screen to new design

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#616]
Update the image confirmation screen found in ImageConfirmationScreen.kt (pending creation) based on the design here: https://www.sketch.com/s/a0bbeac0-767a-4873-beef-c6c7ffd5826a/a/Gmddmgw

Functionality for the Note button will be part of another task.

**Comment by EngrTaofeek** [comment]
Should this update apply to both ImageReviewScreen.kt file and TreeImageReviewScreen.kt file

**Comment by Elforama** [comment]
Yes, both should be updated.
