### ISSUE TITLE
Dashboard upload bar

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#645]
The upload bar shown in this file (https://www.sketch.com/s/a0bbeac0-767a-4873-beef-c6c7ffd5826a/a/ELGGLko/play) needs to be implemented.

The progress should represent the amount of trees left to upload out of all the trees on the device.
The number under the arc is the amount left to upload.

The progress bar should animate as items are uploaded.

**Comment by MarcellinoCO** [comment]
I'll take this task 😀
