### ISSUE TITLE
Update placeholder images/icons

### ISSUE THREAD

**Issue by EngrTaofeek** [Greenstand/treetracker-android#689]
Placeholder icons should be replaced with the ones here https://www.figma.com/file/MVOa55UzwarkicQCyjnXnY/Untitled?node-id=0%3A1  
and implementation to match existing design https://www.sketch.com/s/a0bbeac0-767a-4873-beef-c6c7ffd5826a

**Comment by Elforama** [comment]
These are all placeholder images still. We are still waiting on final images.

**Comment by ZavenArra** [comment]
Final image are available in figma now.

**Comment by ZavenArra** [comment]
Need image assets exported by alexander or gwen or katie

**Comment by ZavenArra** [comment]
Image assets are in Figma: https://www.figma.com/file/hn67qtbMN1aP3yrXx69dP2/Android-UX---Messaging-Edits---Greenstand-v01.05?node-id=1%3A851
