### ISSUE TITLE
Setup retrofit for messaging API

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#694]
The messaging feature of the app will use a REST API. To do this we need to first setup our networking layer.

TODO:
- Setup retrofit for our API (gson, suspending function return types)
- API reference -> https://github.com/Greenstand/treetracker-messaging-api/blob/main/docs/api/spec/treetracker-messaging-api.yaml
- Setup the /messages endpoint to return the JSON data

This task does not connect the network layer to anything in the app, just sets it up. But feel free to do so for testing purposes.

The end result is an api package added to the project that contains a method that returns the messages for a given user using the /message endpoint.

**Comment by ZavenArra** [comment]
Needs testing
