### ISSUE TITLE
Weak GPS signal while tracking trees

### ISSUE THREAD

**Issue by EngrTaofeek** [Greenstand/treetracker-android#698]
If a user attempts to use the app to capture trees where there is weak GPS signal, the app crashes. Common scenario is using the tracking indoors where gps is generally weak. The app crashes after showing convergence timed out in the logs.

From the Locations.kt file, handle situation where convergence times out and show user message or dialog showing possible reasons for failing to track.
Also prevent users from saving images of trees without locations.

**Comment by arunbakt** [comment]
@EngrTaofeek , I tried to modify the configuration for convergence timeout and convergence thresholds and triggered the converge timeout in the app. But the app didn't crash while taking the tree pictures in my Google pixel as well as samsung galaxy.
Seems like this isn't a convergence triggered crash, must be something else. Did you observe it in a specific phone? Is there more information on this? Thank you!

**Comment by arunbakt** [comment]
If you are not aware of the ability to mofidy the config values, you can get to it by double tapping on the build link in the about page of the app. A password prompt will pop up, (xxxx pinged in slack) is the password to change its values.

**Comment by EngrTaofeek** [comment]
Hi @arunbakt I made this PR https://github.com/Greenstand/treetracker-android/pull/699 to fix this issue. Kindly check it out and the commit message.

**Comment by arunbakt** [comment]
Hi @EngrTaofeek , I see the code base I had was older one compared to what exists in master(main) branch. I also see Jonathan has reviewed and requested changes to your PR. So I will let him merge the changes once you address those changes requested.
