### ISSUE TITLE
GPS does not get enabled on pressing OK button of dialog in MainActivity.

### ISSUE THREAD

**Issue by amit88265** [Greenstand/treetracker-android#70]

**Comment by amit88265** [comment]
Hi there anyone maintaining this project. I found it and want to fix it along with many issue of this project but there is no means to reach out to you guys. I also mailed at support@treetracker.com but I found that my mail did not deliver to this address. Because of this I have to write this stuff here.

**Comment by deepwinter** [comment]
Hi Amit, please using the slack link found here and come say hi our slack channels!  Thanks for joining!

https://github.com/Greenstand/Development-Overview/blob/master/Contributing.md
