### ISSUE TITLE
Need to move dialog up to avoid keyboard layover

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#704]
There is a lot of space on the top of the screen which should be utilized to reduce the number of clicks one has to go through to enter the details/login. Lets move it all up to the top.
![Screenshot_20211210_073418_org greenstand android TreeTracker test](https://user-images.githubusercontent.com/3283800/145530323-f93b589c-b471-44fb-a636-285b68faa9ed.jpg)

See screenshot:

**Comment by Elforama** [comment]
There might be a way to avoid the keyboard covering the input another way.

**Comment by Elforama** [comment]
Let's make this so that the input border is no longer covered by the keyboard.
