### ISSUE TITLE
Crash on messaging selection and selfie image roatated

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#705]
When clicking on the next arrow the app crashes see screenshot. And selfie image is rotated
![Screenshot_20211210_095548_org greenstand android TreeTracker test](https://user-images.githubusercontent.com/3283800/145531184-f769a5c4-f734-4430-a703-15a8486de256.jpg)

**Comment by EngrTaofeek** [comment]
Sorry for the bad experience. The messaging features have not being completed as they were not on the 2.0 milestone. I would take a look at it.
