### ISSUE TITLE
Need for a better top section UX

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#706]
This top section needs to not break up Treetracker and the language selector could be in another line rather. Ideally we also show the greenstand logo here next to Treetracker.
![Screenshot_20211210_100307_org greenstand android TreeTracker test](https://user-images.githubusercontent.com/3283800/145532030-58c9a93f-2b40-46aa-98b8-c2ba69addfd9.jpg)

**Comment by Elforama** [comment]
What if we replace Treetracker with the logo?

**Comment by Davidezrajay** [comment]
Replacing text with Logo is cool!
