### ISSUE TITLE
Spinning waiting sign not visible and controls need a dark background

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#708]
The light green spnning waiting icon is not visible well enough. It has to either have a dark background or be much thicker.
Also the controls on the bottom need a permanent dark background (opacity based) to stand out more. Should the controls (back and take picture) be disabled while the spinning spinner spins?
![Screenshot_20211210_102430_org greenstand android TreeTracker test](https://user-images.githubusercontent.com/3283800/145534731-fe75c721-0800-4d00-a360-94c61643fcd1.jpg)

**Comment by peakvalleytech** [comment]
How about placing a white or black semi-transparent overlay over the image?
