### ISSUE TITLE
Image size too small for plant identification

### ISSUE THREAD

**Issue by camwebb** [Greenstand/treetracker-android#711]
Some time between July 2021 and Oct 2021 the size of all the images taken in Haiti dropped to 360 x 480 px. I also checked for Tanzania and all recent images I sampled are also 360 x 480 px. This size is too small to allow reliable seedling identification by human eye. Previous images were usually 960 x 720 px (or larger), which is a sufficiently large image for identification. Please reconsider the image size if species labeling is a goal.

**Comment by Elforama** [comment]
@EngrTaofeek  Can you please look into this and get the images to save around 960 x 720 px or something close to it?
