### ISSUE TITLE
Hide Msg button if not debug

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#718]
The Message feature is for 2.1. For 2.0 we should hide it if the build is not a debug build.

When it's hidden, the reset of the UI should be unchanged.

**Comment by EngrTaofeek** [comment]
![Screenshot](https://user-images.githubusercontent.com/38661872/147609909-fa1ce225-3177-464b-a3fb-be3ef46c2fab.jpeg)
@Elforama 
This is a screenshot of what it would look like in release mode. It looks a bit distorted. Should we leave the messaging button, then add a "Coming soon" text and make it do nothing when clicked. Just to avoid the unnecessary empty space and distorted Track button as shown in the  screenshot.

**Comment by EngrTaofeek** [comment]
@Elforama I redesigned the dashboard to look like this without the message button. It looks much better than having a lot of space or excessively big button
<img width="1440" alt="Screenshot 2022-01-11 at 21 48 28" src="https://user-images.githubusercontent.com/38661872/149019396-215e762e-7fa6-4ffa-bb4d-d69ba8909c6d.png">
Ignore the progress bar I used a placeholder as it wasn't imported properly on Figma. Do you approve of this?

**Comment by Elforama** [comment]
This is Gwen's call. But looks good to me.

**Comment by ZavenArra** [comment]
Approved by Gwen for v2.0
