### ISSUE TITLE
Create a generic treetracker styled dialog

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#728]
All our dialogs are placeholders until design makes something. For the time being we need to make a generic dialog that uses the depth button which can be reused for all our use cases.

Something like:
TreeTrackerDialog(onPositiveAction: () -> Unit, onNegativeAction: () -> Unit, content: @Composable () -> Unit)

**Comment by EngrTaofeek** [comment]
@Elforama check out this designs I created on Figma for the custom dialogs.   https://www.figma.com/file/G2L5XnKeuMV9ADUbdJIxYn/Custom-Dialog?node-id=0%3A1

I would combine all to a single one with compose whereby just adding the right parameters would construct each respectively. What do you think?

**Comment by Elforama** [comment]
These look great, but I have a few critiques..
- we don't need the red x button on top right
- we should avoid words for the buttons. All other action buttons use icons. Maybe the thumbs up and down?

**Comment by EngrTaofeek** [comment]
Okay I would effect these changes then make them on Compose.
