### ISSUE TITLE
Image Resizing

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#73]
We are looking for solutions: 

Many photos are showing up too blurry, out of focus or with not enough resolution to identify tree species. User input, hardware issues? 

The app is designed to reduce the image size to about 100K because they are sent over extremely poor connections.

Most photos show up at 30-100k. In general photos between 30k through 60k photos are not enough resolution to identify details about the tree. 

https://www.treetracker.org/images/4765.jpg
https://www.treetracker.org/images/4762.jpg

## Possible solutions

-  feedback to the user, asking them to try to take a better photo if sharpness is low
- Machine learning

https://stackoverflow.com/questions/21107560/simple-way-to-check-if-an-image-bitmap-is-blur

**Comment by deepwinter** [comment]
This is an old ticket.  Blurry images are a result of user behavior, not resolution.  If there is a solution, it is in analyzing if the autofocus on the camera is being using correctly.

**Comment by deepwinter** [comment]
Solutions here for the generation of android Camera class we are currently using
https://stackoverflow.com/questions/23553445/android-auto-focus-when-continuous-auto-focus-modes-are-not-supported

Note that android Camera has been updated to Camera2 and we should port our code up to that new library.

**Comment by Davidezrajay** [comment]
I believe this ticket has been addressed with blur detection and a camera upgrade.
https://github.com/Greenstand/treetracker-android/issues/207
https://github.com/Greenstand/treetracker-android/pull/141
