### ISSUE TITLE
Email/Phone selection button is not to spec

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#733]
The two button solution currently in the app does not follow the design closely enough.
- Buttons should be combined as in a switch
- Text should be bold
- Do not use gray color, use colors in spec
- Drop shadow should also makes use of vertical sides of button, as in the spec
- The widget in the app should look just like the spec

![image](https://user-images.githubusercontent.com/364622/148616223-209445e0-3d0d-4e66-a5fa-a1ce4caa7c6b.png)

Gwen has offered to give additional support here.

**Comment by Elforama** [comment]
For now I think we can focus on the aspects such as color/font, etc..

The merged design here is unclear. How would it animated?
