### ISSUE TITLE
Need 'View the Live Webmap' link on phone/email screen

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#734]
A link to 'treetracker.org' should be provided on the phone/email screen (in the chosen language), if and only if the device is connected to the internet.

![image](https://user-images.githubusercontent.com/364622/148616722-efd21e34-eff7-4e7c-8735-38ff6d7b1078.png)

**Comment by Elforama** [comment]
I think this can be a 2.1 feature.

**Comment by Elforama** [comment]
To detect internet we can refer to this post: https://stackoverflow.com/questions/4238921/detect-whether-there-is-an-internet-connection-available-on-android

To provide the objects mentioned in the post, we can set them up in the AppModule file for dependency injection.

All the logic to show/hide the link should be in that screens viewmodel.

To open the link in the browser you can look at https://stackoverflow.com/questions/3004515/sending-an-intent-to-browser-to-open-specific-url

**Comment by sidsharma2002** [comment]
this should be a one-shot check for the internet or else we should also check if the connectivity changes? like if I enter the screen without internet and then connect to the wifi the text should appear and vice versa when the wifi is turned off? 

(My thoughts are that the user is not going to be on this screen for a long time anyway)

**Comment by Elforama** [comment]
I think a one shot check is fine

**Comment by sidsharma2002** [comment]
please close this issue
