### ISSUE TITLE
Allow entry of a wallet ID on the wallet select screen

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#741]
In addition to implementing selection of a wallet already registered to the app, the user should be able to manually enter a wallet id for the tracking session.

![image](https://user-images.githubusercontent.com/364622/148619831-770f025e-321c-487a-8075-a84e7e72f3da.png)

**Comment by EngrTaofeek** [comment]
@ZavenArra the wallet name been entered would it be a new user or for an existing user?

**Comment by EngrTaofeek** [comment]
The wallet name/identifier is not filled explicitly by the planters so they might not be aware of their wallet names. Instead of inputting the wallet name it might be better to just use a search bar/box to query for the wallet where the text input does not have to be accurate. What do you think?

**Comment by ZavenArra** [comment]
It's a direct type in for now, because the user is not online.

**Comment by ZavenArra** [comment]
We just want to populate target_wallet in the session with whatever has been typed in, we don't want/need to create a wallet registration on the phone.

**Comment by EngrTaofeek** [comment]
@Elforama I was thinking of bringing back that orange add button in the walletSelect screen so clicking it goes to add Wallet name identifier manually as requested by @ZavenArra in this issue?

**Comment by Elforama** [comment]
This is fine. However, we should wait to do this until https://github.com/Greenstand/treetracker-android/pull/748 is merged. That PR has a large update for how sessions work. The current code does not care about the destination wallet, so it can't be completed until the above PR is merged.

**Comment by ZavenArra** [comment]
why was this issue closed?
