### ISSUE TITLE
Upload progress specification

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#742]
The tree counters and upload progress bar on the dashboard are not working correctly.

Wrong:
![image](https://user-images.githubusercontent.com/364622/148621063-0a249616-2f5e-410c-bd16-8b371c967221.png)

Right:
![image](https://user-images.githubusercontent.com/364622/148621078-98ed5a5e-b48e-4b9b-9805-d1e9e141e55a.png)

**Comment by Elforama** [comment]
@ZavenArra The logic for this does not match how uploads work, so we need to make a change somewhere.

We upload in batches of 50. We first upload each image one by one. We then upload all 50 of the tree meta data in a batch of 50. Once the meta data is uploaded, it's "synced".

The loading indicator relies on the image uploads. This allows it to constantly update so it doesn't look frozen. However, the number of total synced trees needs to rely on what is truly uploaded, and that happens in batches of 50.

The result is the progress bar updating every second. But the top number updating every 8 seconds or so. It looks strange.
