### ISSUE TITLE
Possible Issue With Log in page

### ISSUE THREAD

**Issue by beastlyCoder** [Greenstand/treetracker-android#77]
![screenshot_2018-04-13-11-15-36](https://user-images.githubusercontent.com/15794743/38751256-565227b4-3f0c-11e8-855c-57238b6a30f2.png)

Shouldn't the sign up button be below the Log in since the main focus is the login?

**Comment by Davidezrajay** [comment]
This UI certainly needs to be reworked. Thanks for pointing it out.

This page should focus on **Sign up** 

Once a phone is logged into the app it remains logged in - there is no **log out** function. So the only time users login is required is if they have deleted the app or are uploading it on another phone. 

Thanks for joining the project. If you would like to join us on our Slack channel there is a link here as well https://github.com/Greenstand/Development-Overview/blob/master/Contributing.md

**Comment by deepwinter** [comment]
Closing this out as wont fix.
