### ISSUE TITLE
Database Migration bug

### ISSUE THREAD

**Issue by EngrTaofeek** [Greenstand/treetracker-android#782]
The app crashes when you try to debug the latest version if you have an older debug version installed. it shows the error below. 
<img width="1440" alt="Screenshot 2022-02-17 at 07 47 21" src="https://user-images.githubusercontent.com/38661872/154423448-983d2835-2fae-4217-858c-4c127c23ac87.png">

I tried to reproduce the bug in the release version by installing version 134 and trying to update to 137 and got this instead. 
![WhatsApp Image 2022-02-17 at 08 11 14](https://user-images.githubusercontent.com/38661872/154424147-0243e337-658c-413a-9f48-4d207883a7ed.jpeg)

**Comment by Elforama** [comment]
You need to delete the old app. This is only a bug if this bug happens when updating from the store version
