### ISSUE TITLE
Selfie image rotation

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#790]
The selfie image is rotate 90 degrees on Huawei Y9
This bug also appeared on another Huawei device

This bug is probably Huawei specific, and not mission critical for M2.0

**Comment by EngrTaofeek** [comment]
@ZavenArra it works well on my device. @Elforama how is it on your device? let me ask on the slack to confirm it not just your device.

**Comment by ZavenArra** [comment]
duplicate
