### ISSUE TITLE
Provide Swahili translation for v2.0

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#792]
English: https://github.com/Greenstand/treetracker-android/blob/master/app/src/main/res/values/strings.xml

Swahili: https://github.com/Greenstand/treetracker-android/blob/master/app/src/main/res/values-sw/strings.xml

Node that the existing Swahili file has some older translated text from the v1.0 app.  The new file must have translations for all strings present in the current English file at https://github.com/Greenstand/treetracker-android/blob/master/app/src/main/res/values/strings.xml

**Comment by sebastiangaertner** [comment]
i have done the translation and the latest build 142 was showing the text correctly. Some small changes that i had to add was part of #818 . I will keep testing towards new builds.
