### ISSUE TITLE
Upload progress bar functionality is not quite right

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#796]
The upload progress bar should be FULL whenever we return to the dashboard and are NOT syncing.   The full progress bar represents the number of captures there were queued to be uploaded, not the total number of captures on the device.

![image](https://user-images.githubusercontent.com/364622/155036396-d7d425c9-76fd-4af6-95ee-3872711f8984.png)

**Comment by ZavenArra** [comment]
It seem like this might only occur when the user leaves the tracking process via an atypical route (like changing users and then backing out from there.)

**Comment by ZavenArra** [comment]
Possibly the same issue as https://github.com/Greenstand/treetracker-android/issues/799

**Comment by arunbakt** [comment]
I fixed the ratio used in drawing the orange arc in the dashboard. Earlier it used to be treesSynced/totalTrees should have been treesToSync/totalTrees.  But I believe someone else fixed it already, I ran into a commit merge conflict. I don't believe this happens  when changing users, atleast for me.

**Comment by Elforama** [comment]
@ZavenArra The description you have here is different from what was originally designed. 

Originally it would only reset the progress when completing/exiting a session. The new description seems a bit too aggressive "reset progress when you enter dashboard and are not syncing". This means entering any screen, and then backing out resets the progress. This seems unintuitive.

**Comment by Elforama** [comment]
@ZavenArra The progress bar will update even if content is uploading. That is correct since the newly planted trees are automatically going to be uploaded as long as it's in progres.

**Comment by ZavenArra** [comment]
Ok that makes sense.  Closing this one out, I think the progress bar is working nicely.
