### ISSUE TITLE
alternative return paths to dashboard do not update capture count

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#799]
To reproduce:

1. Enter tracking mode, select a user, select a target wallet
2. Track one tree
3. Track another tree
4. Click the user icon to change users
5. Click the finger pointing back button
**6. Trees not added to upload countdown bar (total is 0 but should be 2)**
7.  Enter tracking mode again, select a user, select a target wallet
8. Track one tree
9. Track another tree
10. Exit tracking mode by click the finger pointing back button 
**11. Upload countdown bar now shows 4 trees (from both sessions)**

**Comment by Elforama** [comment]
What path?

**Comment by Elforama** [comment]
Are you testing this with the fake tree planting button?

**Comment by Elforama** [comment]
I think this feature is working correctly. It's just that legacy trees are considered uploaded by a different status which is messing with the UI. If you only plant manually it should be working (only 2.0 trees). Once users upload all legacy trees the UI will have no more issues.

**Comment by ZavenArra** [comment]
Verified this issue is not related to the legacy trees.  Update with steps to reproduce.
