### ISSUE TITLE
Verify update from store version to new version does not crash

### ISSUE THREAD

**Issue by Elforama** [Greenstand/treetracker-android#803]
Before launching, we MUST verify that updating the app does not crash it. A lot of changes have taken places since the old version so we should test this.

Steps:
- switch to the last release branch and deploy the app to phone (make sure all internal settings are cleared before doing so)
- switch to latest master and deploy to phone. You should be able to use it normally without crashes (especially related to DB migrations)

**Comment by ZavenArra** [comment]
I have verified this, and so has Ezra.

We have having some field users also verify, and then this issue can be closed.

**Comment by ZavenArra** [comment]
Many people have verified this now.  There appears to be no issue.
