### ISSUE TITLE
v2 bulk pack needs device configuration implementation

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#815]
A new device configuration should be saved to the local database the following times:
* App installation
* App upgrade
* Android system upgrade

The most recent device configuration should be associated with a session when a session begins.  Sessions must have a valid device configuration id (device_configuration_id: <uuid> ) to be ingested into the treetracker database. 

Device configuration records have the following format:
```
{
         "id" : <uuid>
         "brand":"google",
         "model":"Pixel",
         "device":"sailfish",
         "serial":"unknown",
         "hardware":"sailfish",
         "app_build":111,
         "instance_id":"dndz8wECMK8",
         "app_version":"1.2.8",
         "manufacturer":"Google",
         "os_version":"9",
         "sdk_version":28,
         "device_identifier":"4f4d6a8b6433e4ca",
         "logged_at" : <ISO 8601>
      }
```

**Comment by Elforama** [comment]
@ZavenArra I think we can simplify this by saving a new device config for each session (required when seeing there is a "logged at" field.

This will avoid issues with installations/upgrades/system updates since the latest will always be logged when starting the session.

**Comment by ZavenArra** [comment]
I think that's fine.
If the device configurations will always be created with the session, then we could have included them in the session object.   I was thinking that we would want to only log these values at the specified times because that's when the data changes as some kind of savings, but I agree it makes the implementation more complicated.

I don't want to change the bulk pack system for this next release, but in the future could consider collapsing the changeable fields into the session, and only sending a single device record on the first upload with the static fields.   For M2.0 let's do as you suggest.

**Comment by Elforama** [comment]
@ZavenArra  Sounds good. So to summarize...
- Remove logged_at field from deviceConfig
- Add start_time to session
- Add end_time to session? (do we want this?)
