### ISSUE TITLE
Speed up initial capture

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#826]
The initial capture of a session is slow because the GPS has just been enabled.  This means that it take longer for our convergence algorithm to converge the location measurement.   Should we leave GPS on when we are on the dashboard, or does this incur too much of a battery cost?  We definitely do not want to save the full planter track except for when they are tracking.   Is there another way to leave the GPS in a low power mode that will improve convergence times?

**Comment by ZavenArra** [comment]
Yeah I am thinking we do need to have the GPS running while we are on the dashboard, just not logging to a tree until the capture session starts.

There is the normal delay incurred by our convergence, but also stopping and starting the GPS causes the GPS radio itself to take a bit longer to stabilize itself.

**Comment by EngrTaofeek** [comment]
@ZavenArra going by this we would have the GPS running all through the app from SignUp/Dashboard till the app is exited.

**Comment by Elforama** [comment]
I think we should have the location updates START when we enter the user select screen, and STOP when entering dashboard. This will allow some time for GPS convergence to warm up while a user selects their profile/wallet/org...

NOTE: We need to make sure we're pausing GPS updates when the app is backgrounded.

There is a problem though (and why there are a lot of session ID crashes currently). The userId and sessionId is used to stamp each location update. The session doesn't start until we begin planting trees, and the user doesn't exist until selected, so it's null until then.

I suggest two approaches.
1. We capture location updates without sessionId/userId while not in a session.
2. We capture location updates without sessionId/userId while not in a session, but once in a session we update those location points with the current userId/sessionId

**Comment by EngrTaofeek** [comment]
@Elforama very helpful notes. I was just about to check your PR that fixed the previous sessionID crash and see if there is a relation with the current one.

**Comment by ZavenArra** [comment]
We don't need to save locations at all when we are not in a session.  Running the GPS (regardless of saving) will warm up the GPS to improve convergence, but we don't need to save those points.    The only location we want to save that would not have a session attached is the single location attached to a new wallet registration.  This location does NOT need to run through our custom convergence logic, it can just be whatever the GPS reports - that will be good enough.

**Comment by EngrTaofeek** [comment]
@Elforama does this fix any bug or prevent any crash
<img width="1425" alt="Screenshot 2022-03-06 at 19 18 56" src="https://user-images.githubusercontent.com/38661872/156936563-a7c99ef4-69d6-452c-8840-303b8f96cfdf.png">

**Comment by EngrTaofeek** [comment]
Fixed and released in 3.2 release
