### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by jbeguna04** [Greenstand/treetracker-android#83]
Hi good day! I would like to ask for your permission to propose a new designs of logo in your application/project. I would like to help projects in open-source .I would just like to propose new designs. Hoping for your positive response Thank You!

**Comment by deepwinter** [comment]
greetings!  Come on over to our Slack channel and chat with others on our design team!  We'd never turn down such an offer, but it might be best to coordinate with people working on design issues.. Mostly here on github it's coders!

**Comment by jbeguna04** [comment]
Thnak you for the reply, github issue is the way to communicate with you. If you would like, ill submit designs here

**Comment by Davidezrajay** [comment]
Thanks, You can submit here. 

If you want to join the full conversation follow this link,
[Volunteer Signup Form](https://docs.google.com/forms/d/e/1FAIpQLSe61HDJKVH16vtTxhXpbwCH-wTVN1e6XoVU1riWjJ-ne5SIiA/viewform?usp=sf_link)

Thanks for you help

**Comment by jbeguna04** [comment]
![image](https://user-images.githubusercontent.com/35353768/39801644-70dadc2e-539e-11e8-9873-07f34b6be561.png)
Hello Good day, This my proposal for the project. Sorry for the wait
Im open to all of your suggestions
Thank You

**Comment by deepwinter** [comment]
@Davidezrajay Please address this and close it out.   I believe we got so many logo redesigns because it is for people's classwork.
