### ISSUE TITLE
Session request object changes

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#834]
API changes on the backend require a tweak to session request object

Instead of sending 'wallet' we require 'originating_wallet_registration_id'.  We could consider keeping 'wallet' in the payload anyway for redundancy in case of any data loss.

**Comment by ZavenArra** [comment]
it looks like  the following was added to WalletRegistrationRequest instead of SessionRequest object

@SerializedName("originating_wallet_registration_id")
    val walletId: String,

**Comment by Elforama** [comment]
Oops, will fix that

**Comment by ZavenArra** [comment]
I may have fixed this myself already, testing now..
