### ISSUE TITLE
CameraActivity.java line 342 org.greenstand.android.TreeTracker.activities.CameraActivity.onClick(5 crashes)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#84]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void android.hardware.Camera.takePicture(android.hardware.Camera$ShutterCallback, android.hardware.Camera$PictureCallback, android.hardware.Camera$PictureCallback)' on a null object reference
org.greenstand.android.TreeTracker.activities.CameraActivity.onClick (CameraActivity.java:342)  | android.view.View.performClick (View.java:5698)
android.view.View$PerformClick.run (View.java:22523)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:158)
android.app.ActivityThread.main (ActivityThread.java:7230)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker.debug_issue_31_crash_5AD43AB302B6000130C08684841394D3_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1935112/org.greenstand.android.treetracker.debug_issue_31_crash_5AD43AB302B6000130C08684841394D3_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
Device- Galaxy J1, OS- 6.0.1
App Version- Version 1.1.6 (27)
Fabric error- # 31

**Comment by deepwinter** [comment]
This error is not appearing in the current build.
