### ISSUE TITLE
CameraActivity.java line 169 org.greenstand.android.TreeTracker.activities.CameraActivity.checkBlurriness(2 crashes)

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#85]
Fatal Exception: java.lang.IllegalArgumentException
x must be >= 0

android.graphics.Bitmap.checkXYSign (Bitmap.java:408)
android.graphics.Bitmap.getPixel (Bitmap.java:1622)
org.greenstand.android.TreeTracker.activities.CameraActivity.checkBlurriness (CameraActivity.java:169)
org.greenstand.android.TreeTracker.activities.CameraActivity.onPictureTaken (CameraActivity.java:144)
android.hardware.Camera$EventHandler.handleMessage (Camera.java:1135)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)

**Comment by Surbhi79** [comment]
[org.greenstand.android.treetracker.debug_issue_41_crash_5AD1229D018200011A4F61F44E2953BC_DNE_0_v2.txt](https://github.com/Greenstand/treetracker-android/files/1935114/org.greenstand.android.treetracker.debug_issue_41_crash_5AD1229D018200011A4F61F44E2953BC_DNE_0_v2.txt)

**Comment by Surbhi79** [comment]
Device- Emulator
App Version- Version 1.1.6 (21)
Fabric error- # 41

**Comment by beastlyCoder** [comment]
I am not able to find the code where it check bluriness in the photo, has this been merged to the code yet? I tried re cloning the project and didn't see it on line 169.

**Comment by Surbhi79** [comment]
@beastlyCoder It's my mistake. This issue is from an emulator so the code may or may not exist. In this case, the code is not.
