### ISSUE TITLE
Address green language button in top right

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#852]
UX says: this shouldn't be green
But the buttons on the language screen itself ARE green now
Decide what to do in M2.1

**Comment by KelvnPere** [comment]
Hello @ZavenArra @Elforama i will like to work on this. Is this issue available?

**Comment by Elforama** [comment]
Go for it

**Comment by KelvnPere** [comment]
@ZavenArra Can i get a UI for this? I'm trying to locate that in the app? Which if this describes that?
![Screenshot_20220302-215308](https://user-images.githubusercontent.com/36895007/156448057-0a510d0b-1c29-4c6f-ae7e-50f2fff00df5.png | width=100)

**Comment by EngrTaofeek** [comment]
@KelvnPere it is in the TextButton.kt file. Alternatively just double tap shift and search for LanguageButton you would see two composable that should be what you want to modify

**Comment by ZavenArra** [comment]
I think this ticket needs a decision in design review from @snacks

**Comment by EngrTaofeek** [comment]
Conclusion was to leave as it was if I remember correctly
