### ISSUE TITLE
User already existing down thumb button should pop to user selection screen

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#865]

**Comment by Elforama** [comment]
Do we want this? If they down thumb it, it probably means they typed something wrong and want to retype it, not get sent back a screen.

**Comment by ZavenArra** [comment]
ok maybe I'm wrong about that, I will test again.

**Comment by Elforama** [comment]
@ZavenArra following up here. Perhaps we want Gwens thoughts on this?

**Comment by ZavenArra** [comment]
Yep you are right, and we display the existing user already.  No change needed
