### ISSUE TITLE
Strange behavior with upload counter

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#870]
Video can be seen here: https://greenstand.slack.com/archives/CJ0DSKZLH/p1646256249521509?thread_ts=1646248622.302339&cid=CJ0DSKZLH

**Comment by Tarek-Bohdima** [comment]
**_The tested Device related to this issue:_**
Samsung Galaxy Note 9 , Android 10

**_Steps taken to stop the crash:_**
Disable installed services in the Accessibility setting : services that need to overlay like password managers and authenticator apps and live transcribe  
![Screenshot_20220304-212826_Accessibility](https://user-images.githubusercontent.com/33880180/156849357-e1141463-ee07-49ce-9ced-52706bc491bd.jpg)
