### ISSUE TITLE
Planter identifier should be case insensitive 

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#871]
lowercase all text entered in the 'email' before storing to the internal mobile database or checking for pre-existing wallet registrations.

**Comment by Elforama** [comment]
@ZavenArra Do we want to update the text to always show it as lowercase? Or should they be able to type uppercase, but internally save it as lower case?

I think we should force the UI to show only lowercase

**Comment by ZavenArra** [comment]
I agree, force the UI to only show lowercase.
