### ISSUE TITLE
Detect absence of GPS unit

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#876]
Some phones doesn't have a GPS unit

The older version of the app has some logic to detect that there is no GPS unit.   This can be determined by asking the location service which providers are available.

https://github.com/Greenstand/treetracker-android/tree/release

**Comment by EngrTaofeek** [comment]
@ZavenArra should we restrict devices that don't have the gps device from using the app at all or just restrict them from using the tree capturing device.

**Comment by ZavenArra** [comment]
Restrict them from using the app.
