### ISSUE TITLE
Add haptics

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#877]
Haptics:
Vibrate once when click on take picture button in camera
Vibrate twice once the GPS coordinate is converged

Vibrate once when upload sync is initiated
Vibrate twice when upload sync is finished

**Comment by Elforama** [comment]
Should this be for all buttons?

**Comment by peakvalleytech** [comment]
@ZavenArra @Elforama Sorry, new to the project. What does haptics refer to and how should this be implemented?

**Comment by Elforama** [comment]
It refers to the phone vibrating.

Here is an example https://www.geeksforgeeks.org/how-to-vibrate-a-device-programmatically-in-android/

**Comment by peakvalleytech** [comment]
@Elforama Yeah, I can work on this one. Can you get @ZavenArra to confirm that this is indeed what is required?

**Comment by ZavenArra** [comment]
Updated with some basic haptics, basically what the old app has.

The idea here to get some basic haptics in, and then the UX will be reviewed later to improve the.   Open to other suggestions.
