### ISSUE TITLE
New Logo Design For Tree Tracker

### ISSUE THREAD

**Issue by sametceylan** [Greenstand/treetracker-android#88]
Hello sir, my name is Samet Ceylan and I am a designer. If you want and let me, I want to design a creative logo for Tree Tracker. I want you to know that I will do it for you. I do not want any compensation. If you would like me to design and if you have any particular detail, please contact me.

**Comment by Davidezrajay** [comment]
Hello Samet, 
We do need a new logo for the Tree Tracker app, there have been several versions floating around. 
We have other designer needs as well if you would like to join us you can follow this link. 

https://github.com/Greenstand/Development-Overview/blob/master/Contributing.md

**Comment by deepwinter** [comment]
Closing this ticket.
