### ISSUE TITLE
white_leaf.png and yellow_leafs_placeholder.png are incorrectly imported

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#883]
white_leaf.png and yellow_leafs_placeholder.png drawables are incorrectly imported, leading to a crash on some phones.

replacing these in the code with the save_btn drawable solves the crash (but of course with the wrong image).

How can these be correctly imported?   

It looks like we don't have a specific icon resource in figma for this, so it may be that the original file was not created correctly.

**Comment by EngrTaofeek** [comment]
That's very odd considering both white_leaf.png, yellow_leafs_placeholder.png and save_btn are all png files. Is the error on firebase Crashlytics? so I can take a look.

**Comment by ZavenArra** [comment]
Fix for #902 seems to have resolved this.
