### ISSUE TITLE
First time I press upload, no snack message shows.

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#888]

**Comment by sebastiangaertner** [comment]
Can confirm this

**Comment by sidsharma2002** [comment]
@Elforama can you guide me on this?

**Comment by sidsharma2002** [comment]
@Elforama in the dashboardViewModel, I changed the _isSyncing's initial value from null to false. The issue seems to be solved, is there a specific reason why its init value was null rather than false ? if not I'll raise the Pr
