### ISSUE TITLE
Tree 384, 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#89]
test database
tree 384, is inaccurately placed (by ten meters or so) on the map and is missing from the Android app for user 5
WHY????

id  |      time_created      | time_updated | missing | priority | cause_of_death_id | user_id | primary_location_id | settings_id | override_settings_id | dead |     lat      |      lon       |            estimated_geometric_location            | gps_accuracy | active |                                                                   image_url                                                                   | certificate_id
-----+------------------------+--------------+---------+----------+-------------------+---------+---------------------+-------------+----------------------+------+--------------+----------------+----------------------------------------------------+--------------+--------+-----------------------------------------------------------------------------------------------------------------------------------------------+----------------
384 | 2018-04-29 08:54:07+00 |              |         |          |                   |       5 |                     |             |                      |    0 | 61.173482972 | -149.948590778 | 0101000020E6100000DF2C0CDB5ABE62C03C90A5B034964E40 |            6 | t      | https://treetracker-dev.nyc3.digitaloceanspaces.com/2018.04.29.13.12.18_815b1023-ac50-442f-a7f1-d5a57b66e075_IMG_20180429_125404_61544667.jpg
https://treetracker-dev.nyc3.digitaloceanspaces.com/2018.04.29.13.12.18_815b1023-ac50-442f-a7f1-d5a57b66e075_IMG_20180429_125404_61544667.jpg
|

**Comment by deepwinter** [comment]
@Davidezrajay are you sure these were uploaded to the right treetracker site?  User 5 is Sam, but this record references treetracker-dev cloud storage.  Are we sure this is the right database?

**Comment by Davidezrajay** [comment]
Not sure what is going on here. This was taken on a dev model.. I'll test and try to duplicate. Close for now
