### ISSUE TITLE
"Click on the button to add note" ...  is missing in strings.xml

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#894]
See screenshot in swahili. 
Can not find this message "click on the button to add note" in any strings.xml (missing in the english values as well) therefore it must be hard coded. 
https://github.com/Greenstand/treetracker-android/blob/master/app/src/main/res/values/strings.xml

![Screenshot_20220308_084154_org greenstand android TreeTracker test](https://user-images.githubusercontent.com/3283800/157174411-dfbbd841-9dc4-44b5-be95-8ddae753450a.jpg)

**Comment by ZavenArra** [comment]
@sebastiangaertner need Swahili translation for this string

**Comment by sebastiangaertner** [comment]
@ZavenArra 

Bonyeza kitufe ili kuongeza taarifa

**Comment by KelvnPere** [comment]
@EngrTaofeek here

**Comment by EngrTaofeek** [comment]
@KelvnPere in the Tutorial.kt file. The TreeCaptureReview() composable to be exact there is an hardcoded string there extract it to a string resource and add the Swahili translation as said earlier in the comment.

**Comment by EngrTaofeek** [comment]
> @ZavenArra
> 
> bonyeza kitufe ili kuongeza taarifa

@KelvnPere this is the Swahili translation

**Comment by KelvnPere** [comment]
https://github.com/Greenstand/treetracker-android/pull/911
