### ISSUE TITLE
Update About Page Text

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#90]
Please add the following text to the about page.

"This tree tracking planter app is made to track planted trees while supporting people and organizations that plant, monitor and protect trees. 

Take a picture of your trees and then press sync and your tree data will be uploaded to a map at www.treetracker.org. 

Visit www.GreenStand.org for more details on how this system works.

Your app requires 10 meters of accuracy to take a photo. 

Email: info@greenstand.com for more access to your data, or a web link with your specific trees. 

This app is under development by Zaven Arra and his cool team of volunteers at GreenStand.org. 

Developers can find the open source project code at www.github.com/greenstand"

**Comment by beastlyCoder** [comment]
so you don't want anything already in the about page to be replaced?
