### ISSUE TITLE
Keyboard cuts off input on chat screen on some phones

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#931]

**Comment by sebastiangaertner** [comment]
Additionally the back button does not work and once selected there is no way to get out of the screen yet

**Comment by ZavenArra** [comment]
> Additionally the back button does not work and once selected there is no way to get out of the screen yet

Should be filed as a separate issue.  But also it's been fixed now.

**Comment by EngrTaofeek** [comment]
@ZavenArra please describe with more details, preferably a screenshot would help.

**Comment by Elforama** [comment]
@EngrTaofeek this is a general app wide issue. Sometimes the keyboard can cover the text input. It can cover it fully or partially.
