### ISSUE TITLE
Add Location Functionality for Non - Google Devices

### ISSUE THREAD

**Issue by dezidaisy** [Greenstand/treetracker-android#95]
Link: https://blog.smaato.com/optimize-your-location-data-accuracy/
Issue: AOSP Android.Location API
If you expect to deploy your application on non-Google Android devices (like the Amazon Kindle Fire), then you'll need to use the AOSP android.location APIs. Documentation on pulling user location using the android.location package can be found here.

**Comment by deepwinter** [comment]
We do not plan to support AOSP devices at this time.  Closing this one out, we can return to this in the future if there are non-Android users we need to support.
