### ISSUE TITLE
Picture only taken when the GPS convergence is fully processed

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#969]
Take an image of a tree and move the phone. The camera will only be triggered x seconds after clicking the shutter button. 
Results in random pictures due to movement of the phone after shutter is clicked. 

Expected workflow: Image is taken and convergence calculated and attached to the data point. 

Version 1.4.2 was handling this correctly.

**Comment by Elforama** [comment]
This is not a bug. This is required for accurate tracking data.

**Comment by Davidezrajay** [comment]
@sebastiangaertner This was implemented this way to refine the accuracy of the location of the photo.

Is it that you have to wait for the convergence or that after you click the photo, there is a delay before it takes it?

**Comment by EngrTaofeek** [comment]
issue closed with @Davidezrajay COMMENT
