### ISSUE TITLE
Move GPS Accuracy Block / Location Recording to Camera Page

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#97]
The 'within 10 meters' GPS Accuracy read out and block should be on camera page and should record location at the time of the photo. 

This issues should replace the current function which blocks the user from opening the camera when the GPS accuracy is not within 10 meters. It also records image located at the time of opening the camera.  

The intent of this ticket is to create the point as close to the actual location of the image as possible.

**Comment by deepwinter** [comment]
This has been resolved.  Image location is set immediately after the camera capture closes (in onActivityResult)
