### ISSUE TITLE
Visualize convergence while capturing

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-android#970]
When waiting for convergence while capturing an image of tree, we want to show a graphic that indicated how convergence is progressing toward an acceptable level, and indicate that the camera must be held still.

A graphic that is always shown indicating to hold the camera still is probably necessary.

Additionally, use the following match to display improvement in convergence until 100% converged

percent converged = min(100, 100 * convergence_target_value /  current_convergence_value)

**Comment by EngrTaofeek** [comment]
@ZavenArra I think the instruction on holding the camera still should also be included in the tutorials also. I would work on this issue

**Comment by ZavenArra** [comment]
OK great

**Comment by EngrTaofeek** [comment]
![](https://user-images.githubusercontent.com/38661872/165352881-1085eff2-f13a-45d3-a0f6-284246efb0aa.jpeg)
![](https://user-images.githubusercontent.com/38661872/165352891-3fbf6a57-5e28-4ed4-aca1-5cc6b0fe42a6.jpeg)
@ZavenArra and @sebastiangaertner  this what this PR does adds a dark background to the progress bar and shows the percentage converged along with instruction once the capture button is clicked.

**Comment by ZavenArra** [comment]
I would like to release this PR and make it available for testers and use that to drive feedback.  @Elforama what do you think about adopting a process along those lines?

**Comment by EngrTaofeek** [comment]
fixed in #972
