### ISSUE TITLE
VALIDATION FAILS FROM ACTION BUTTON original issue "Depth Button Scope Bug #984"

### ISSUE THREAD

**Issue by EngrTaofeek** [Greenstand/treetracker-android#977]
After email/phone input credentials are validated properly when clicked on done button from keyboard but shows error when clicking action right arrow button. Validation and error message should work both from the keyboard and action button.

**Comment by ZavenArra** [comment]
https://github.com/Greenstand/treetracker-android/pull/979

**Comment by EngrTaofeek** [comment]
fixed in #1000
