### ISSUE TITLE
Playstore policy privacy listing and link in the app

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#983]
The old app had the privacy policy linked which is not the case in the new version. This is pretty vital and we have gotton an email with a deadline 

The email to us is [here ->](https://notifications.google.com/g/vib/AD-FnEypQvbJb97DySCI3kwizTd4v7gGDBotu8lpNTBQ-igvdTtp-tPs4Y4DncETfR1Am6gSfBzHgWdHl3g28usN1xaZONMEq6K4mauij-eXynIRv5lRkdTn3yaxIDh-lAkEGX_nWu3j4ijSr1P45BRHrxNQoDeyMhUWPtBMtmek_bfJtIlTNGqqTqWUtGyQTnUKAvMYXPXcaIYKC1xhJSdzX2iWjgirEWOEfmdgpwGfi8sCl5U8ZV7gETDsbyXTsi6c_yjsFyCW6-PXuw0iS1UPHo0W_9hhFW9aBbzr8evotSw)

Article on Google on what is required is [here - >](https://support.google.com/googleplay/android-developer/answer/10144311?visit_id=637910463971666611-888402202&rd=1)

**Comment by sebastiangaertner** [comment]
https://support.google.com/googleplay/android-developer/answer/10787469?hl=en#other&zippy=%2Cother-app-and-data-disclosures

Can someone answer if we encrypt the data when transferring ?

**Comment by Davidezrajay** [comment]
``<string name="policy_text_blob" translatable="false">

                            GreenStand - Privacy Policy
            \n

    How We Handle Data:
            \n

    Our primary goals are to use data to create a greener earth and offer an option for economic opportunity in areas of extreme poverty. We believe that the scientific and project related data we collect (that is not private by nature) should be freely available to the public. Unless otherwise authorized we will not disclose sensitive user information, such as contact information. Our primary data collection is focused around scientific research and creating a transparent system to collect field data related to the survival processes of trees as well as any information related to the systematic harvesting of tree related products. This information includes planter geo-tagged, time-stamped photos and other user entered data.
            \n

    By using our services, you are agreeing to allow us to use your environmentally related information and make it publicly accessible via websites. User’s first name and/or organization name may be displayed with the corresponding tree data. With prior consent, other user related information may be displayed. Upon request all user data may be hidden from public view. Phone numbers and/or email addresses may be used by GreenStand to contact planters, but will not be shared with third parties without prior consent.
            \n
            \n

    Project Related/Scientific Data:
            \n
    
    GreenStand upholds an open scientific data policy and intends to make any scientific finding, that may positively affect the environment and/or social welfare, freely available. Using data we receive through user inputs on our mobile applications, website and database systems, we intended to identify problems, solutions and trends in environmental/social health. By using our services and software, you are thereby agreeing to allow us to publicly display project related data and scientific findings. In the event that data collected with this software is sensitive, please contact us at Info@greenstand.org so that we may act accordingly.
            \n
            \n

    How We Collect Data:
            \n

    Mobile Applications:
            \n

    Photos: time-stamped, Geo-tagged.

            \n
    User entered information: name, email address, organization name, phone number, field notes.
            \n

    App settings for users
            \n

    Application analytics: software crash reports, phone make and model.
            \n

    Website Application: Database entries, general analytics.
            \n

    Donor supplied information
            \n
            \n

    User Data We Collect:
            \n

    Information relating to individual users or organizations will not be disclosed without prior consent. We are handling all user related data (full name, phone numbers, email) securely using modern cryptography. Planter’s full names and contact information will never be shared without prior consent.
            \n

    Personal Information: On our tree tracker app we require a name, and email, and optionally a phone number and an organization name. All personal data is stored in a secure database.
            \n

    Mobile App users: Our mobile apps collect the following personal information: User entered information: name, email address, organization name, phone number.
            \n

    Donor information: When you make a donation we collect information that is used solely for accounting, tax reporting and donation processing purposes. This information is guarded with utmost care and will not be sold, shared or traded with any other entity. We do abide by IRS requirement to disclose limited information that is mandated to be available on public taxes records. Donor information may also be disclosed at the donor\'s request. We collect the following donor information: name, address, amount of donation, any other personal information given to us.
            \n

    User Photos:
            \n

    GreenStand’s tree tracking program runs on the collection of time-stamped, geotagged photos. This information is stored in a secure database from which it is displayed in the form of a tree map. We also use this information to generate statistics related to tree planting. We are only interested in tree-related photos, please don’t send us anything else. With the proper use of this system, all photo taken will relate to environmental data and GreenStand does not consider or treat uploaded photos as “user data.” By using our mobile application you are agreeing to allow us to use your photos.
            \n
            \n
    User Data Deletion:
            \n
            \n
    To request your data be deleted, contact Info@greenstand.org . Note, the complete removal of all personal data is only possible before tree capture data tokenization.
            \n
            \n
    Changes to the Policy
            \n
            \n
    It is our intent to hold the principles of this policy, but we do understand there may be a need to change it from time to time. Changes will be posted on our website as soon as possible.
            \n
            \n
    © 2022 GreenStand (registered 501(c)3 nonprofit. EIN: 47-3150283 ). Info@greenstand.org
            \n
    Privacy Policy

        </string>

**Comment by EngrTaofeek** [comment]
fixed in #987
