### ISSUE TITLE
Create Select Organisation Screen

### ISSUE THREAD

**Issue by EngrTaofeek** [Greenstand/treetracker-android#989]
Create select organization screen. The screen should be populated from the list of organizations that would have been added to the database after deep linking. Check Figma file for design.

**Comment by Elforama** [comment]
@EngrTaofeek please link share a screenshot of the design here.

**Comment by EngrTaofeek** [comment]
@Elforama  https://www.figma.com/file/hn67qtbMN1aP3yrXx69dP2/Android-UX-(v2---w%2F-messaging-1.0.5)?node-id=0%3A386 
<img width="1440" alt="Screenshot 2022-07-25 at 10 23 14" src="https://user-images.githubusercontent.com/38661872/180744193-3ed7cfb7-495a-475b-8313-212be63e1bd7.png">
