### ISSUE TITLE
Minor Edge Case: Session not being uploaded

### ISSUE THREAD

**Issue by Kpoke** [Greenstand/treetracker-android#996]
There are currently failing bulk packs, two cases where the capture uploaded is referencing a session that has not been uploaded. It seemed like a particular session was omitted when the sessions were uploaded.

**Comment by Kpoke** [comment]
I can confirm that the session for one of the packs was later uploaded and the pack was processed

**Comment by EngrTaofeek** [comment]
@Kpoke that is great.  I checked the code out earlier today trying to check for possible loop holes which I didn't find. So it is safe to assume it was probably an internet disconnection issue while uploading/syncing from the app.

**Comment by Kpoke** [comment]
Yes I believe it is same to assume so @EngrTaofeek
